// AUTO-GENERATED by scripts/sync-printful.mjs — do not edit by hand.
// Source: Printful "Evolve" store. Re-run the script to refresh.
import type { Product } from "./products";

export const PRINTFUL_PRODUCTS: Product[] = [
  {
    "slug": "treeline-camo-trucker",
    "name": "Treeline Camo Trucker",
    "subtitle": "Headwear · made to order",
    "category": "headwear",
    "collection": "boreal",
    "price": 3300,
    "externalId": "441089440",
    "tagline": "Descended from survivors.",
    "description": "Treeline Camo Trucker — Descended from survivors. Printed and embroidered to order, then shipped across Canada and the continent.",
    "details": [
      "Made to order — printed/embroidered on demand",
      "Ships across Canada & North America",
      "1 colourway · sizes One size",
      "EVOLVE artwork — earned outside"
    ],
    "tone": [
      "#0d3b1f",
      "#00ff41"
    ],
    "images": [
      "/products/p441089440-0.png"
    ],
    "sizes": [
      "One size"
    ],
    "variants": [
      {
        "id": "treeline-camo-trucker-camo-olive-one-size",
        "variantId": "5362675264",
        "sku": "6A377452C4E15",
        "size": "One size",
        "color": "Camo/Olive",
        "swatch": "#3d4a2b",
        "inStock": true
      }
    ]
  },
  {
    "slug": "longhaul-hoodie",
    "name": "Longhaul Hoodie",
    "subtitle": "Outerwear · made to order",
    "category": "outerwear",
    "collection": "peaks",
    "price": 5450,
    "externalId": "441089080",
    "tagline": "Built for the bush. Made for the long haul.",
    "description": "Longhaul Hoodie — Built for the bush. Made for the long haul. Printed and embroidered to order, then shipped across Canada and the continent.",
    "details": [
      "Made to order — printed/embroidered on demand",
      "Ships across Canada & North America",
      "1 colourway · sizes S, M, L, XL, 2XL",
      "EVOLVE artwork — earned outside"
    ],
    "tone": [
      "#13233a",
      "#4ade80"
    ],
    "images": [
      "/products/p441089080-0.png"
    ],
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "variants": [
      {
        "id": "longhaul-hoodie-carbon-grey-s",
        "variantId": "5362674524",
        "sku": "6A3773EE4302A_S",
        "size": "S",
        "color": "Carbon Grey",
        "swatch": "#44474a",
        "inStock": true
      },
      {
        "id": "longhaul-hoodie-carbon-grey-m",
        "variantId": "5362674525",
        "sku": "6A3773EE4302A_M",
        "size": "M",
        "color": "Carbon Grey",
        "swatch": "#44474a",
        "inStock": true
      },
      {
        "id": "longhaul-hoodie-carbon-grey-l",
        "variantId": "5362674526",
        "sku": "6A3773EE4302A_L",
        "size": "L",
        "color": "Carbon Grey",
        "swatch": "#44474a",
        "inStock": true
      },
      {
        "id": "longhaul-hoodie-carbon-grey-xl",
        "variantId": "5362674527",
        "sku": "6A3773EE4302A_XL",
        "size": "XL",
        "color": "Carbon Grey",
        "swatch": "#44474a",
        "inStock": true
      },
      {
        "id": "longhaul-hoodie-carbon-grey-2xl",
        "variantId": "5362674528",
        "sku": "6A3773EE4302A_2XL",
        "size": "2XL",
        "color": "Carbon Grey",
        "swatch": "#44474a",
        "inStock": true
      }
    ]
  },
  {
    "slug": "coldfront-champion-long-sleeve",
    "name": "Coldfront Champion Long-Sleeve",
    "subtitle": "Tops · made to order",
    "category": "tops",
    "collection": "prairies",
    "price": 4750,
    "externalId": "441087767",
    "tagline": "Earned outside.",
    "description": "Coldfront Champion Long-Sleeve — Earned outside. Printed and embroidered to order, then shipped across Canada and the continent.",
    "details": [
      "Made to order — printed/embroidered on demand",
      "Ships across Canada & North America",
      "1 colourway · sizes S, M, L, XL, 2XL",
      "EVOLVE artwork — earned outside"
    ],
    "tone": [
      "#3a2f12",
      "#39ff14"
    ],
    "images": [
      "/products/p441087767-0.png"
    ],
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "variants": [
      {
        "id": "coldfront-champion-long-sleeve-white-s",
        "variantId": "5362668206",
        "sku": "6A3771D05A41F_S",
        "size": "S",
        "color": "White",
        "swatch": "#ece9e2",
        "inStock": true
      },
      {
        "id": "coldfront-champion-long-sleeve-white-m",
        "variantId": "5362668207",
        "sku": "6A3771D05A41F_M",
        "size": "M",
        "color": "White",
        "swatch": "#ece9e2",
        "inStock": true
      },
      {
        "id": "coldfront-champion-long-sleeve-white-l",
        "variantId": "5362668208",
        "sku": "6A3771D05A41F_L",
        "size": "L",
        "color": "White",
        "swatch": "#ece9e2",
        "inStock": true
      },
      {
        "id": "coldfront-champion-long-sleeve-white-xl",
        "variantId": "5362668209",
        "sku": "6A3771D05A41F_XL",
        "size": "XL",
        "color": "White",
        "swatch": "#ece9e2",
        "inStock": true
      },
      {
        "id": "coldfront-champion-long-sleeve-white-2xl",
        "variantId": "5362668210",
        "sku": "6A3771D05A41F_2XL",
        "size": "2XL",
        "color": "White",
        "swatch": "#ece9e2",
        "inStock": true
      }
    ]
  },
  {
    "slug": "driftwood-hooded-long-sleeve",
    "name": "Driftwood Hooded Long-Sleeve",
    "subtitle": "Tops · made to order",
    "category": "tops",
    "collection": "coast",
    "price": 4100,
    "externalId": "441087198",
    "tagline": "Canadian-built. Weather-tested.",
    "description": "Driftwood Hooded Long-Sleeve — Canadian-built. Weather-tested. Printed and embroidered to order, then shipped across Canada and the continent.",
    "details": [
      "Made to order — printed/embroidered on demand",
      "Ships across Canada & North America",
      "1 colourway · sizes XS, S, M, L, XL, 2XL",
      "EVOLVE artwork — earned outside"
    ],
    "tone": [
      "#0c2c33",
      "#00ff41"
    ],
    "images": [
      "/products/p441087198-0.png"
    ],
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "variants": [
      {
        "id": "driftwood-hooded-long-sleeve-charcoal-black-triblend-xs",
        "variantId": "5362665594",
        "sku": "6A3770D5D397C_XS",
        "size": "XS",
        "color": "Charcoal-Black Triblend",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "driftwood-hooded-long-sleeve-charcoal-black-triblend-s",
        "variantId": "5362665595",
        "sku": "6A3770D5D397C_S",
        "size": "S",
        "color": "Charcoal-Black Triblend",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "driftwood-hooded-long-sleeve-charcoal-black-triblend-m",
        "variantId": "5362665597",
        "sku": "6A3770D5D397C_M",
        "size": "M",
        "color": "Charcoal-Black Triblend",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "driftwood-hooded-long-sleeve-charcoal-black-triblend-l",
        "variantId": "5362665598",
        "sku": "6A3770D5D397C_L",
        "size": "L",
        "color": "Charcoal-Black Triblend",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "driftwood-hooded-long-sleeve-charcoal-black-triblend-xl",
        "variantId": "5362665599",
        "sku": "6A3770D5D397C_XL",
        "size": "XL",
        "color": "Charcoal-Black Triblend",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "driftwood-hooded-long-sleeve-charcoal-black-triblend-2xl",
        "variantId": "5362665600",
        "sku": "6A3770D5D397C_2XL",
        "size": "2XL",
        "color": "Charcoal-Black Triblend",
        "swatch": "#0a0a0a",
        "inStock": true
      }
    ]
  },
  {
    "slug": "summit-full-zip-hoodie",
    "name": "Summit Full-Zip Hoodie",
    "subtitle": "Outerwear · made to order",
    "category": "outerwear",
    "collection": "boreal",
    "price": 5250,
    "externalId": "441085408",
    "tagline": "Strip it back. Build it stronger.",
    "description": "Summit Full-Zip Hoodie — Strip it back. Build it stronger. Printed and embroidered to order, then shipped across Canada and the continent.",
    "details": [
      "Made to order — printed/embroidered on demand",
      "Ships across Canada & North America",
      "1 colourway · sizes S, M, L, XL, 2XL, 3XL",
      "EVOLVE artwork — earned outside"
    ],
    "tone": [
      "#0d3b1f",
      "#00ff41"
    ],
    "images": [
      "/products/p441085408-0.png"
    ],
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL",
      "3XL"
    ],
    "variants": [
      {
        "id": "summit-full-zip-hoodie-charcoal-heather-s",
        "variantId": "5362657742",
        "sku": "6A376D492E307_S",
        "size": "S",
        "color": "Charcoal Heather",
        "swatch": "#8a9099",
        "inStock": true
      },
      {
        "id": "summit-full-zip-hoodie-charcoal-heather-m",
        "variantId": "5362657743",
        "sku": "6A376D492E307_M",
        "size": "M",
        "color": "Charcoal Heather",
        "swatch": "#8a9099",
        "inStock": true
      },
      {
        "id": "summit-full-zip-hoodie-charcoal-heather-l",
        "variantId": "5362657744",
        "sku": "6A376D492E307_L",
        "size": "L",
        "color": "Charcoal Heather",
        "swatch": "#8a9099",
        "inStock": true
      },
      {
        "id": "summit-full-zip-hoodie-charcoal-heather-xl",
        "variantId": "5362657745",
        "sku": "6A376D492E307_XL",
        "size": "XL",
        "color": "Charcoal Heather",
        "swatch": "#8a9099",
        "inStock": true
      },
      {
        "id": "summit-full-zip-hoodie-charcoal-heather-2xl",
        "variantId": "5362657746",
        "sku": "6A376D492E307_2XL",
        "size": "2XL",
        "color": "Charcoal Heather",
        "swatch": "#8a9099",
        "inStock": true
      },
      {
        "id": "summit-full-zip-hoodie-charcoal-heather-3xl",
        "variantId": "5362657747",
        "sku": "6A376D492E307_3XL",
        "size": "3XL",
        "color": "Charcoal Heather",
        "swatch": "#8a9099",
        "inStock": true
      }
    ],
    "badge": "Flagship"
  },
  {
    "slug": "heritage-classic-tee",
    "name": "Heritage Classic Tee",
    "subtitle": "Tops · made to order",
    "category": "tops",
    "collection": "peaks",
    "price": 1600,
    "externalId": "441085023",
    "tagline": "Cold and free beats warm and bored.",
    "description": "Heritage Classic Tee — Cold and free beats warm and bored. Printed and embroidered to order, then shipped across Canada and the continent.",
    "details": [
      "Made to order — printed/embroidered on demand",
      "Ships across Canada & North America",
      "1 colourway · sizes S, M, L, XL, 2XL, 3XL",
      "EVOLVE artwork — earned outside"
    ],
    "tone": [
      "#13233a",
      "#4ade80"
    ],
    "images": [
      "/products/p441085023-0.png"
    ],
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL",
      "3XL"
    ],
    "variants": [
      {
        "id": "heritage-classic-tee-natural-s",
        "variantId": "5362656022",
        "sku": "6A376C77437A5_S",
        "size": "S",
        "color": "Natural",
        "swatch": "#e6dcc6",
        "inStock": true
      },
      {
        "id": "heritage-classic-tee-natural-m",
        "variantId": "5362656023",
        "sku": "6A376C77437A5_M",
        "size": "M",
        "color": "Natural",
        "swatch": "#e6dcc6",
        "inStock": true
      },
      {
        "id": "heritage-classic-tee-natural-l",
        "variantId": "5362656024",
        "sku": "6A376C77437A5_L",
        "size": "L",
        "color": "Natural",
        "swatch": "#e6dcc6",
        "inStock": true
      },
      {
        "id": "heritage-classic-tee-natural-xl",
        "variantId": "5362656025",
        "sku": "6A376C77437A5_XL",
        "size": "XL",
        "color": "Natural",
        "swatch": "#e6dcc6",
        "inStock": true
      },
      {
        "id": "heritage-classic-tee-natural-2xl",
        "variantId": "5362656026",
        "sku": "6A376C77437A5_2XL",
        "size": "2XL",
        "color": "Natural",
        "swatch": "#e6dcc6",
        "inStock": true
      },
      {
        "id": "heritage-classic-tee-natural-3xl",
        "variantId": "5362656027",
        "sku": "6A376C77437A5_3XL",
        "size": "3XL",
        "color": "Natural",
        "swatch": "#e6dcc6",
        "inStock": true
      }
    ]
  },
  {
    "slug": "deepwoods-heavyweight-hoodie",
    "name": "Deepwoods Heavyweight Hoodie",
    "subtitle": "Outerwear · made to order",
    "category": "outerwear",
    "collection": "prairies",
    "price": 5800,
    "externalId": "441084646",
    "tagline": "Where the signal dies, we come alive.",
    "description": "Deepwoods Heavyweight Hoodie — Where the signal dies, we come alive. Printed and embroidered to order, then shipped across Canada and the continent.",
    "details": [
      "Made to order — printed/embroidered on demand",
      "Ships across Canada & North America",
      "1 colourway · sizes XS, S, M, L, XL, 2XL, 3XL",
      "EVOLVE artwork — earned outside"
    ],
    "tone": [
      "#3a2f12",
      "#39ff14"
    ],
    "images": [
      "/products/p441084646-0.png"
    ],
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "2XL",
      "3XL"
    ],
    "variants": [
      {
        "id": "deepwoods-heavyweight-hoodie-army-xs",
        "variantId": "5362654378",
        "sku": "6A376BCE469F2_XS",
        "size": "XS",
        "color": "Army",
        "swatch": "#4b5320",
        "inStock": true
      },
      {
        "id": "deepwoods-heavyweight-hoodie-army-s",
        "variantId": "5362654379",
        "sku": "6A376BCE469F2_S",
        "size": "S",
        "color": "Army",
        "swatch": "#4b5320",
        "inStock": true
      },
      {
        "id": "deepwoods-heavyweight-hoodie-army-m",
        "variantId": "5362654380",
        "sku": "6A376BCE469F2_M",
        "size": "M",
        "color": "Army",
        "swatch": "#4b5320",
        "inStock": true
      },
      {
        "id": "deepwoods-heavyweight-hoodie-army-l",
        "variantId": "5362654381",
        "sku": "6A376BCE469F2_L",
        "size": "L",
        "color": "Army",
        "swatch": "#4b5320",
        "inStock": true
      },
      {
        "id": "deepwoods-heavyweight-hoodie-army-xl",
        "variantId": "5362654382",
        "sku": "6A376BCE469F2_XL",
        "size": "XL",
        "color": "Army",
        "swatch": "#4b5320",
        "inStock": true
      },
      {
        "id": "deepwoods-heavyweight-hoodie-army-2xl",
        "variantId": "5362654383",
        "sku": "6A376BCE469F2_2XL",
        "size": "2XL",
        "color": "Army",
        "swatch": "#4b5320",
        "inStock": true
      },
      {
        "id": "deepwoods-heavyweight-hoodie-army-3xl",
        "variantId": "5362654384",
        "sku": "6A376BCE469F2_3XL",
        "size": "3XL",
        "color": "Army",
        "swatch": "#4b5320",
        "inStock": true
      }
    ]
  },
  {
    "slug": "nightfall-snapback",
    "name": "Nightfall Snapback",
    "subtitle": "Headwear · made to order",
    "category": "headwear",
    "collection": "coast",
    "price": 3150,
    "externalId": "441084360",
    "tagline": "Work hard. Play harder. Get outside.",
    "description": "Nightfall Snapback — Work hard. Play harder. Get outside. Printed and embroidered to order, then shipped across Canada and the continent.",
    "details": [
      "Made to order — printed/embroidered on demand",
      "Ships across Canada & North America",
      "1 colourway · sizes One size",
      "EVOLVE artwork — earned outside"
    ],
    "tone": [
      "#0c2c33",
      "#00ff41"
    ],
    "images": [
      "/products/p441084360-0.png"
    ],
    "sizes": [
      "One size"
    ],
    "variants": [
      {
        "id": "nightfall-snapback-heather-grey-one-size",
        "variantId": "5362652623",
        "sku": "6A376B3FB75A3",
        "size": "One size",
        "color": "Heather Grey",
        "swatch": "#8a9099",
        "inStock": true
      }
    ]
  },
  {
    "slug": "whiteout-organic-tee",
    "name": "Whiteout Organic Tee",
    "subtitle": "Tops · made to order",
    "category": "tops",
    "collection": "boreal",
    "price": 3550,
    "externalId": "441084054",
    "tagline": "Restore what the week wore down.",
    "description": "Whiteout Organic Tee — Restore what the week wore down. Printed and embroidered to order, then shipped across Canada and the continent.",
    "details": [
      "Made to order — printed/embroidered on demand",
      "Ships across Canada & North America",
      "1 colourway · sizes One size",
      "EVOLVE artwork — earned outside"
    ],
    "tone": [
      "#0d3b1f",
      "#00ff41"
    ],
    "images": [
      "/products/p441084054-0.png"
    ],
    "sizes": [
      "One size"
    ],
    "variants": [
      {
        "id": "whiteout-organic-tee-black-one-size",
        "variantId": "5362651251",
        "sku": "6A376AB07E34E",
        "size": "One size",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      }
    ]
  },
  {
    "slug": "ridgeline-snapback",
    "name": "Ridgeline Snapback",
    "subtitle": "Headwear · made to order",
    "category": "headwear",
    "collection": "peaks",
    "price": 3100,
    "externalId": "441083649",
    "tagline": "Tougher than the winters that made us.",
    "description": "Ridgeline Snapback — Tougher than the winters that made us. Printed and embroidered to order, then shipped across Canada and the continent.",
    "details": [
      "Made to order — printed/embroidered on demand",
      "Ships across Canada & North America",
      "1 colourway · sizes One size",
      "EVOLVE artwork — earned outside"
    ],
    "tone": [
      "#13233a",
      "#4ade80"
    ],
    "images": [
      "/products/p441083649-0.png"
    ],
    "sizes": [
      "One size"
    ],
    "variants": [
      {
        "id": "ridgeline-snapback-dark-grey-one-size",
        "variantId": "5362649362",
        "sku": "6A376A2850E8E",
        "size": "One size",
        "color": "Dark Grey",
        "swatch": "#5b5f63",
        "inStock": true
      }
    ]
  },
  {
    "slug": "stormcheck-packable-jacket",
    "name": "Stormcheck Packable Jacket",
    "subtitle": "Outerwear · made to order",
    "category": "outerwear",
    "collection": "prairies",
    "price": 7800,
    "externalId": "441082795",
    "tagline": "From the wheat to the water.",
    "description": "Stormcheck Packable Jacket — From the wheat to the water. Printed and embroidered to order, then shipped across Canada and the continent.",
    "details": [
      "Made to order — printed/embroidered on demand",
      "Ships across Canada & North America",
      "1 colourway · sizes S",
      "EVOLVE artwork — earned outside"
    ],
    "tone": [
      "#3a2f12",
      "#39ff14"
    ],
    "images": [
      "/products/p441082795-0.png"
    ],
    "sizes": [
      "S"
    ],
    "variants": [
      {
        "id": "stormcheck-packable-jacket-black-s",
        "variantId": "5362646673",
        "sku": "6A37692B2230C",
        "size": "S",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      }
    ]
  },
  {
    "slug": "backcountry-trucker",
    "name": "Backcountry Trucker",
    "subtitle": "Headwear · made to order",
    "category": "headwear",
    "collection": "coast",
    "price": 3250,
    "externalId": "441082547",
    "tagline": "Some things should never change. Get outside.",
    "description": "Backcountry Trucker — Some things should never change. Get outside. Printed and embroidered to order, then shipped across Canada and the continent.",
    "details": [
      "Made to order — printed/embroidered on demand",
      "Ships across Canada & North America",
      "1 colourway · sizes One size",
      "EVOLVE artwork — earned outside"
    ],
    "tone": [
      "#0c2c33",
      "#00ff41"
    ],
    "images": [
      "/products/p441082547-0.png"
    ],
    "sizes": [
      "One size"
    ],
    "variants": [
      {
        "id": "backcountry-trucker-loden-one-size",
        "variantId": "5362645425",
        "sku": "6A3768A50899B",
        "size": "One size",
        "color": "Loden",
        "swatch": "#3d4a2b",
        "inStock": true
      }
    ]
  },
  {
    "slug": "outpost-ringer-tee",
    "name": "Outpost Ringer Tee",
    "subtitle": "Tops · made to order",
    "category": "tops",
    "collection": "boreal",
    "price": 2650,
    "externalId": "441082269",
    "tagline": "Descended from survivors.",
    "description": "Outpost Ringer Tee — Descended from survivors. Printed and embroidered to order, then shipped across Canada and the continent.",
    "details": [
      "Made to order — printed/embroidered on demand",
      "Ships across Canada & North America",
      "1 colourway · sizes S, M, L, XL, 2XL, 3XL",
      "EVOLVE artwork — earned outside"
    ],
    "tone": [
      "#0d3b1f",
      "#00ff41"
    ],
    "images": [
      "/products/p441082269-0.png"
    ],
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL",
      "3XL"
    ],
    "variants": [
      {
        "id": "outpost-ringer-tee-heather-gray-black-s",
        "variantId": "5362644524",
        "sku": "6A37683C61B53_S",
        "size": "S",
        "color": "Heather Gray / Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "outpost-ringer-tee-heather-gray-black-m",
        "variantId": "5362644525",
        "sku": "6A37683C61B53_M",
        "size": "M",
        "color": "Heather Gray / Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "outpost-ringer-tee-heather-gray-black-l",
        "variantId": "5362644526",
        "sku": "6A37683C61B53_L",
        "size": "L",
        "color": "Heather Gray / Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "outpost-ringer-tee-heather-gray-black-xl",
        "variantId": "5362644527",
        "sku": "6A37683C61B53_XL",
        "size": "XL",
        "color": "Heather Gray / Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "outpost-ringer-tee-heather-gray-black-2xl",
        "variantId": "5362644528",
        "sku": "6A37683C61B53_2XL",
        "size": "2XL",
        "color": "Heather Gray / Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "outpost-ringer-tee-heather-gray-black-3xl",
        "variantId": "5362644529",
        "sku": "6A37683C61B53_3XL",
        "size": "3XL",
        "color": "Heather Gray / Black",
        "swatch": "#0a0a0a",
        "inStock": true
      }
    ]
  },
  {
    "slug": "wildmark-organic-tee",
    "name": "Wildmark Organic Tee",
    "subtitle": "Tops · made to order",
    "category": "tops",
    "collection": "peaks",
    "price": 3000,
    "externalId": "440709618",
    "tagline": "Built for the bush. Made for the long haul.",
    "description": "Wildmark Organic Tee — Built for the bush. Made for the long haul. Printed and embroidered to order, then shipped across Canada and the continent.",
    "details": [
      "Made to order — printed/embroidered on demand",
      "Ships across Canada & North America",
      "1 colourway · sizes S, M, L, XL, 2XL",
      "EVOLVE artwork — earned outside"
    ],
    "tone": [
      "#13233a",
      "#4ade80"
    ],
    "images": [
      "/products/p440709618-0.png"
    ],
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "variants": [
      {
        "id": "wildmark-organic-tee-desert-dust-s",
        "variantId": "5360918931",
        "sku": "6A355A69CEBF3_S",
        "size": "S",
        "color": "Desert Dust",
        "swatch": "#3d4a2b",
        "inStock": true
      },
      {
        "id": "wildmark-organic-tee-desert-dust-m",
        "variantId": "5360918932",
        "sku": "6A355A69CEBF3_M",
        "size": "M",
        "color": "Desert Dust",
        "swatch": "#3d4a2b",
        "inStock": true
      },
      {
        "id": "wildmark-organic-tee-desert-dust-l",
        "variantId": "5360918933",
        "sku": "6A355A69CEBF3_L",
        "size": "L",
        "color": "Desert Dust",
        "swatch": "#3d4a2b",
        "inStock": true
      },
      {
        "id": "wildmark-organic-tee-desert-dust-xl",
        "variantId": "5360918934",
        "sku": "6A355A69CEBF3_XL",
        "size": "XL",
        "color": "Desert Dust",
        "swatch": "#3d4a2b",
        "inStock": true
      },
      {
        "id": "wildmark-organic-tee-desert-dust-2xl",
        "variantId": "5360918935",
        "sku": "6A355A69CEBF3_2XL",
        "size": "2XL",
        "color": "Desert Dust",
        "swatch": "#3d4a2b",
        "inStock": true
      }
    ]
  },
  {
    "slug": "trailhead-tank",
    "name": "Trailhead Tank",
    "subtitle": "Tops · made to order",
    "category": "tops",
    "collection": "prairies",
    "price": 2550,
    "externalId": "440708831",
    "tagline": "Earned outside.",
    "description": "Trailhead Tank — Earned outside. Printed and embroidered to order, then shipped across Canada and the continent.",
    "details": [
      "Made to order — printed/embroidered on demand",
      "Ships across Canada & North America",
      "1 colourway · sizes XS, S, M, L, XL, 2XL",
      "EVOLVE artwork — earned outside"
    ],
    "tone": [
      "#3a2f12",
      "#39ff14"
    ],
    "images": [
      "/products/p440708831-0.png"
    ],
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "variants": [
      {
        "id": "trailhead-tank-black-xs",
        "variantId": "5360914569",
        "sku": "6A35595A57F56_XS",
        "size": "XS",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "trailhead-tank-black-s",
        "variantId": "5360914570",
        "sku": "6A35595A57F56_S",
        "size": "S",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "trailhead-tank-black-m",
        "variantId": "5360914571",
        "sku": "6A35595A57F56_M",
        "size": "M",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "trailhead-tank-black-l",
        "variantId": "5360914572",
        "sku": "6A35595A57F56_L",
        "size": "L",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "trailhead-tank-black-xl",
        "variantId": "5360914573",
        "sku": "6A35595A57F56_XL",
        "size": "XL",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "trailhead-tank-black-2xl",
        "variantId": "5360914574",
        "sku": "6A35595A57F56_2XL",
        "size": "2XL",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      }
    ]
  },
  {
    "slug": "whitewood-forest-snapback",
    "name": "Whitewood Forest Snapback",
    "subtitle": "Headwear · made to order",
    "category": "headwear",
    "collection": "coast",
    "price": 3100,
    "externalId": "440708024",
    "tagline": "Canadian-built. Weather-tested.",
    "description": "Whitewood Forest Snapback — Canadian-built. Weather-tested. Printed and embroidered to order, then shipped across Canada and the continent.",
    "details": [
      "Made to order — printed/embroidered on demand",
      "Ships across Canada & North America",
      "1 colourway · sizes One size",
      "EVOLVE artwork — earned outside"
    ],
    "tone": [
      "#0c2c33",
      "#00ff41"
    ],
    "images": [
      "/products/p440708024-0.png"
    ],
    "sizes": [
      "One size"
    ],
    "variants": [
      {
        "id": "whitewood-forest-snapback-white-one-size",
        "variantId": "5360909429",
        "sku": "6A35586B4F8CE",
        "size": "One size",
        "color": "White",
        "swatch": "#ece9e2",
        "inStock": true
      }
    ]
  },
  {
    "slug": "frontier-trucker",
    "name": "Frontier Trucker",
    "subtitle": "Headwear · made to order",
    "category": "headwear",
    "collection": "boreal",
    "price": 3250,
    "externalId": "440613219",
    "tagline": "Strip it back. Build it stronger.",
    "description": "Frontier Trucker — Strip it back. Build it stronger. Printed and embroidered to order, then shipped across Canada and the continent.",
    "details": [
      "Made to order — printed/embroidered on demand",
      "Ships across Canada & North America",
      "1 colourway · sizes One size",
      "EVOLVE artwork — earned outside"
    ],
    "tone": [
      "#0d3b1f",
      "#00ff41"
    ],
    "images": [
      "/products/p440613219-0.png"
    ],
    "sizes": [
      "One size"
    ],
    "variants": [
      {
        "id": "frontier-trucker-loden-one-size",
        "variantId": "5360410273",
        "sku": "6A34D27D2548B",
        "size": "One size",
        "color": "Loden",
        "swatch": "#3d4a2b",
        "inStock": true
      }
    ]
  },
  {
    "slug": "boreal-standard-hoodie",
    "name": "Boreal Standard Hoodie",
    "subtitle": "Outerwear · made to order",
    "category": "outerwear",
    "collection": "peaks",
    "price": 4600,
    "externalId": "440612780",
    "tagline": "Cold and free beats warm and bored.",
    "description": "Boreal Standard Hoodie — Cold and free beats warm and bored. Printed and embroidered to order, then shipped across Canada and the continent.",
    "details": [
      "Made to order — printed/embroidered on demand",
      "Ships across Canada & North America",
      "1 colourway · sizes S, M, L, XL, 2XL",
      "EVOLVE artwork — earned outside"
    ],
    "tone": [
      "#13233a",
      "#4ade80"
    ],
    "images": [
      "/products/p440612780-0.png"
    ],
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "variants": [
      {
        "id": "boreal-standard-hoodie-black-s",
        "variantId": "5360409149",
        "sku": "6A34D1EBCC7D8_S",
        "size": "S",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "boreal-standard-hoodie-black-m",
        "variantId": "5360409150",
        "sku": "6A34D1EBCC7D8_M",
        "size": "M",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "boreal-standard-hoodie-black-l",
        "variantId": "5360409152",
        "sku": "6A34D1EBCC7D8_L",
        "size": "L",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "boreal-standard-hoodie-black-xl",
        "variantId": "5360409153",
        "sku": "6A34D1EBCC7D8_XL",
        "size": "XL",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "boreal-standard-hoodie-black-2xl",
        "variantId": "5360409154",
        "sku": "6A34D1EBCC7D8_2XL",
        "size": "2XL",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      }
    ]
  },
  {
    "slug": "whiteout-v-neck",
    "name": "Whiteout V-Neck",
    "subtitle": "Tops · made to order",
    "category": "tops",
    "collection": "prairies",
    "price": 3100,
    "externalId": "440612001",
    "tagline": "Where the signal dies, we come alive.",
    "description": "Whiteout V-Neck — Where the signal dies, we come alive. Printed and embroidered to order, then shipped across Canada and the continent.",
    "details": [
      "Made to order — printed/embroidered on demand",
      "Ships across Canada & North America",
      "1 colourway · sizes S, M, L, XL, 2XL",
      "EVOLVE artwork — earned outside"
    ],
    "tone": [
      "#3a2f12",
      "#39ff14"
    ],
    "images": [
      "/products/p440612001-0.png"
    ],
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "variants": [
      {
        "id": "whiteout-v-neck-black-s",
        "variantId": "5360406226",
        "sku": "6A34D0C8B3190_S",
        "size": "S",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "whiteout-v-neck-black-m",
        "variantId": "5360406227",
        "sku": "6A34D0C8B3190_M",
        "size": "M",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "whiteout-v-neck-black-l",
        "variantId": "5360406228",
        "sku": "6A34D0C8B3190_L",
        "size": "L",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "whiteout-v-neck-black-xl",
        "variantId": "5360406229",
        "sku": "6A34D0C8B3190_XL",
        "size": "XL",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "whiteout-v-neck-black-2xl",
        "variantId": "5360406230",
        "sku": "6A34D0C8B3190_2XL",
        "size": "2XL",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      }
    ]
  },
  {
    "slug": "woodsmoke-premium-crew",
    "name": "Woodsmoke Premium Crew",
    "subtitle": "Outerwear · made to order",
    "category": "outerwear",
    "collection": "coast",
    "price": 4050,
    "externalId": "440610853",
    "tagline": "Work hard. Play harder. Get outside.",
    "description": "Woodsmoke Premium Crew — Work hard. Play harder. Get outside. Printed and embroidered to order, then shipped across Canada and the continent.",
    "details": [
      "Made to order — printed/embroidered on demand",
      "Ships across Canada & North America",
      "1 colourway · sizes S, M, L, XL, 2XL",
      "EVOLVE artwork — earned outside"
    ],
    "tone": [
      "#0c2c33",
      "#00ff41"
    ],
    "images": [
      "/products/p440610853-0.png"
    ],
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "variants": [
      {
        "id": "woodsmoke-premium-crew-black-s",
        "variantId": "5360402035",
        "sku": "6A34CF011E23B_S",
        "size": "S",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "woodsmoke-premium-crew-black-m",
        "variantId": "5360402036",
        "sku": "6A34CF011E23B_M",
        "size": "M",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "woodsmoke-premium-crew-black-l",
        "variantId": "5360402037",
        "sku": "6A34CF011E23B_L",
        "size": "L",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "woodsmoke-premium-crew-black-xl",
        "variantId": "5360402038",
        "sku": "6A34CF011E23B_XL",
        "size": "XL",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "woodsmoke-premium-crew-black-2xl",
        "variantId": "5360402039",
        "sku": "6A34CF011E23B_2XL",
        "size": "2XL",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      }
    ]
  },
  {
    "slug": "blackout-hoodie",
    "name": "Blackout Hoodie",
    "subtitle": "Outerwear · made to order",
    "category": "outerwear",
    "collection": "boreal",
    "price": 3550,
    "externalId": "440610516",
    "tagline": "Restore what the week wore down.",
    "description": "Blackout Hoodie — Restore what the week wore down. Printed and embroidered to order, then shipped across Canada and the continent.",
    "details": [
      "Made to order — printed/embroidered on demand",
      "Ships across Canada & North America",
      "1 colourway · sizes S, M, L, XL, 2XL",
      "EVOLVE artwork — earned outside"
    ],
    "tone": [
      "#0d3b1f",
      "#00ff41"
    ],
    "images": [
      "/products/p440610516-0.png"
    ],
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "variants": [
      {
        "id": "blackout-hoodie-black-s",
        "variantId": "5360401045",
        "sku": "6A34CE59C1E53_S",
        "size": "S",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "blackout-hoodie-black-m",
        "variantId": "5360401046",
        "sku": "6A34CE59C1E53_M",
        "size": "M",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "blackout-hoodie-black-l",
        "variantId": "5360401047",
        "sku": "6A34CE59C1E53_L",
        "size": "L",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "blackout-hoodie-black-xl",
        "variantId": "5360401048",
        "sku": "6A34CE59C1E53_XL",
        "size": "XL",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "blackout-hoodie-black-2xl",
        "variantId": "5360401049",
        "sku": "6A34CE59C1E53_2XL",
        "size": "2XL",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      }
    ],
    "badge": "Flagship"
  },
  {
    "slug": "anvil-heavyweight-tee",
    "name": "Anvil Heavyweight Tee",
    "subtitle": "Tops · made to order",
    "category": "tops",
    "collection": "peaks",
    "price": 2550,
    "externalId": "440609882",
    "tagline": "Tougher than the winters that made us.",
    "description": "Anvil Heavyweight Tee — Tougher than the winters that made us. Printed and embroidered to order, then shipped across Canada and the continent.",
    "details": [
      "Made to order — printed/embroidered on demand",
      "Ships across Canada & North America",
      "1 colourway · sizes S, M, L, XL, 2XL",
      "EVOLVE artwork — earned outside"
    ],
    "tone": [
      "#13233a",
      "#4ade80"
    ],
    "images": [
      "/products/p440609882-0.png"
    ],
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "variants": [
      {
        "id": "anvil-heavyweight-tee-black-s",
        "variantId": "5360399047",
        "sku": "6A34CD39B4E5B_S",
        "size": "S",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "anvil-heavyweight-tee-black-m",
        "variantId": "5360399048",
        "sku": "6A34CD39B4E5B_M",
        "size": "M",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "anvil-heavyweight-tee-black-l",
        "variantId": "5360399049",
        "sku": "6A34CD39B4E5B_L",
        "size": "L",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "anvil-heavyweight-tee-black-xl",
        "variantId": "5360399050",
        "sku": "6A34CD39B4E5B_XL",
        "size": "XL",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "anvil-heavyweight-tee-black-2xl",
        "variantId": "5360399051",
        "sku": "6A34CD39B4E5B_2XL",
        "size": "2XL",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      }
    ]
  },
  {
    "slug": "trapline-hunting-hoodie",
    "name": "Trapline Hunting Hoodie",
    "subtitle": "Outerwear · made to order",
    "category": "outerwear",
    "collection": "prairies",
    "price": 8650,
    "externalId": "440609698",
    "tagline": "From the wheat to the water.",
    "description": "Trapline Hunting Hoodie — From the wheat to the water. Printed and embroidered to order, then shipped across Canada and the continent.",
    "details": [
      "Made to order — printed/embroidered on demand",
      "Ships across Canada & North America",
      "1 colourway · sizes S, M, L, XL, 2XL",
      "EVOLVE artwork — earned outside"
    ],
    "tone": [
      "#3a2f12",
      "#39ff14"
    ],
    "images": [
      "/products/p440609698-0.png"
    ],
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "variants": [
      {
        "id": "trapline-hunting-hoodie-black-s",
        "variantId": "5360398514",
        "sku": "6A34CCF0BD407_S",
        "size": "S",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "trapline-hunting-hoodie-black-m",
        "variantId": "5360398515",
        "sku": "6A34CCF0BD407_M",
        "size": "M",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "trapline-hunting-hoodie-black-l",
        "variantId": "5360398516",
        "sku": "6A34CCF0BD407_L",
        "size": "L",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "trapline-hunting-hoodie-black-xl",
        "variantId": "5360398517",
        "sku": "6A34CCF0BD407_XL",
        "size": "XL",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "trapline-hunting-hoodie-black-2xl",
        "variantId": "5360398518",
        "sku": "6A34CCF0BD407_2XL",
        "size": "2XL",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      }
    ]
  },
  {
    "slug": "halfday-raglan",
    "name": "Halfday Raglan",
    "subtitle": "Tops · made to order",
    "category": "tops",
    "collection": "coast",
    "price": 3100,
    "externalId": "440609155",
    "tagline": "Some things should never change. Get outside.",
    "description": "Halfday Raglan — Some things should never change. Get outside. Printed and embroidered to order, then shipped across Canada and the continent.",
    "details": [
      "Made to order — printed/embroidered on demand",
      "Ships across Canada & North America",
      "1 colourway · sizes XS, S, M, L, XL, 2XL",
      "EVOLVE artwork — earned outside"
    ],
    "tone": [
      "#0c2c33",
      "#00ff41"
    ],
    "images": [
      "/products/p440609155-0.png"
    ],
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "variants": [
      {
        "id": "halfday-raglan-heather-denim-navy-xs",
        "variantId": "5360396891",
        "sku": "6A34CC2450ED2_XS",
        "size": "XS",
        "color": "Heather Denim/Navy",
        "swatch": "#1f2a3d",
        "inStock": true
      },
      {
        "id": "halfday-raglan-heather-denim-navy-s",
        "variantId": "5360396892",
        "sku": "6A34CC2450ED2_S",
        "size": "S",
        "color": "Heather Denim/Navy",
        "swatch": "#1f2a3d",
        "inStock": true
      },
      {
        "id": "halfday-raglan-heather-denim-navy-m",
        "variantId": "5360396893",
        "sku": "6A34CC2450ED2_M",
        "size": "M",
        "color": "Heather Denim/Navy",
        "swatch": "#1f2a3d",
        "inStock": true
      },
      {
        "id": "halfday-raglan-heather-denim-navy-l",
        "variantId": "5360396894",
        "sku": "6A34CC2450ED2_L",
        "size": "L",
        "color": "Heather Denim/Navy",
        "swatch": "#1f2a3d",
        "inStock": true
      },
      {
        "id": "halfday-raglan-heather-denim-navy-xl",
        "variantId": "5360396895",
        "sku": "6A34CC2450ED2_XL",
        "size": "XL",
        "color": "Heather Denim/Navy",
        "swatch": "#1f2a3d",
        "inStock": true
      },
      {
        "id": "halfday-raglan-heather-denim-navy-2xl",
        "variantId": "5360396896",
        "sku": "6A34CC2450ED2_2XL",
        "size": "2XL",
        "color": "Heather Denim/Navy",
        "swatch": "#1f2a3d",
        "inStock": true
      }
    ]
  },
  {
    "slug": "northcut-v-neck",
    "name": "Northcut V-Neck",
    "subtitle": "Tops · made to order",
    "category": "tops",
    "collection": "boreal",
    "price": 3100,
    "externalId": "440608834",
    "tagline": "Descended from survivors.",
    "description": "Northcut V-Neck — Descended from survivors. Printed and embroidered to order, then shipped across Canada and the continent.",
    "details": [
      "Made to order — printed/embroidered on demand",
      "Ships across Canada & North America",
      "1 colourway · sizes XS, S, M, L, XL, 2XL",
      "EVOLVE artwork — earned outside"
    ],
    "tone": [
      "#0d3b1f",
      "#00ff41"
    ],
    "images": [
      "/products/p440608834-0.png"
    ],
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "variants": [
      {
        "id": "northcut-v-neck-dark-grey-heather-xs",
        "variantId": "5360395777",
        "sku": "6A34CB91E1988_XS",
        "size": "XS",
        "color": "Dark Grey Heather",
        "swatch": "#3a3d41",
        "inStock": true
      },
      {
        "id": "northcut-v-neck-dark-grey-heather-s",
        "variantId": "5360395778",
        "sku": "6A34CB91E1988_S",
        "size": "S",
        "color": "Dark Grey Heather",
        "swatch": "#3a3d41",
        "inStock": true
      },
      {
        "id": "northcut-v-neck-dark-grey-heather-m",
        "variantId": "5360395779",
        "sku": "6A34CB91E1988_M",
        "size": "M",
        "color": "Dark Grey Heather",
        "swatch": "#3a3d41",
        "inStock": true
      },
      {
        "id": "northcut-v-neck-dark-grey-heather-l",
        "variantId": "5360395780",
        "sku": "6A34CB91E1988_L",
        "size": "L",
        "color": "Dark Grey Heather",
        "swatch": "#3a3d41",
        "inStock": true
      },
      {
        "id": "northcut-v-neck-dark-grey-heather-xl",
        "variantId": "5360395781",
        "sku": "6A34CB91E1988_XL",
        "size": "XL",
        "color": "Dark Grey Heather",
        "swatch": "#3a3d41",
        "inStock": true
      },
      {
        "id": "northcut-v-neck-dark-grey-heather-2xl",
        "variantId": "5360395782",
        "sku": "6A34CB91E1988_2XL",
        "size": "2XL",
        "color": "Dark Grey Heather",
        "swatch": "#3a3d41",
        "inStock": true
      }
    ]
  },
  {
    "slug": "great-white-north-tumbler",
    "name": "Great White North Tumbler",
    "subtitle": "Accessories · made to order",
    "category": "accessories",
    "collection": "peaks",
    "price": 3900,
    "externalId": "440607891",
    "tagline": "Built for the bush. Made for the long haul.",
    "description": "Great White North Tumbler — Built for the bush. Made for the long haul. Printed and embroidered to order, then shipped across Canada and the continent.",
    "details": [
      "Made to order — printed/embroidered on demand",
      "Ships across Canada & North America",
      "1 colourway · sizes 20 oz",
      "EVOLVE artwork — earned outside"
    ],
    "tone": [
      "#13233a",
      "#4ade80"
    ],
    "images": [
      "/products/p440607891-0.png"
    ],
    "sizes": [
      "20 oz"
    ],
    "variants": [
      {
        "id": "great-white-north-tumbler-white-20-oz",
        "variantId": "5360390873",
        "sku": "6A34CA51549E9",
        "size": "20 oz",
        "color": "White",
        "swatch": "#ece9e2",
        "inStock": true
      }
    ]
  },
  {
    "slug": "stealth-original-snapback",
    "name": "Stealth Original Snapback",
    "subtitle": "Headwear · made to order",
    "category": "headwear",
    "collection": "prairies",
    "price": 3000,
    "externalId": "440607292",
    "tagline": "Earned outside.",
    "description": "Stealth Original Snapback — Earned outside. Printed and embroidered to order, then shipped across Canada and the continent.",
    "details": [
      "Made to order — printed/embroidered on demand",
      "Ships across Canada & North America",
      "1 colourway · sizes One size",
      "EVOLVE artwork — earned outside"
    ],
    "tone": [
      "#3a2f12",
      "#39ff14"
    ],
    "images": [
      "/products/p440607292-0.png"
    ],
    "sizes": [
      "One size"
    ],
    "variants": [
      {
        "id": "stealth-original-snapback-black-one-size",
        "variantId": "5360389107",
        "sku": "6A34C960682A9",
        "size": "One size",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      }
    ]
  },
  {
    "slug": "stealth-denim-cap",
    "name": "Stealth Denim Cap",
    "subtitle": "Headwear · made to order",
    "category": "headwear",
    "collection": "coast",
    "price": 2550,
    "externalId": "440606458",
    "tagline": "Canadian-built. Weather-tested.",
    "description": "Stealth Denim Cap — Canadian-built. Weather-tested. Printed and embroidered to order, then shipped across Canada and the continent.",
    "details": [
      "Made to order — printed/embroidered on demand",
      "Ships across Canada & North America",
      "1 colourway · sizes One size",
      "EVOLVE artwork — earned outside"
    ],
    "tone": [
      "#0c2c33",
      "#00ff41"
    ],
    "images": [
      "/products/p440606458-0.png"
    ],
    "sizes": [
      "One size"
    ],
    "variants": [
      {
        "id": "stealth-denim-cap-black-one-size",
        "variantId": "5360386477",
        "sku": "6A34C8166FAF9",
        "size": "One size",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      }
    ]
  },
  {
    "slug": "wanderlust-cuff-beanie",
    "name": "Wanderlust Cuff Beanie",
    "subtitle": "Headwear · made to order",
    "category": "headwear",
    "collection": "boreal",
    "price": 2450,
    "externalId": "440605056",
    "tagline": "Strip it back. Build it stronger.",
    "description": "Wanderlust Cuff Beanie — Strip it back. Build it stronger. Printed and embroidered to order, then shipped across Canada and the continent.",
    "details": [
      "Made to order — printed/embroidered on demand",
      "Ships across Canada & North America",
      "1 colourway · sizes One size",
      "EVOLVE artwork — earned outside"
    ],
    "tone": [
      "#0d3b1f",
      "#00ff41"
    ],
    "images": [
      "/products/p440605056-0.png"
    ],
    "sizes": [
      "One size"
    ],
    "variants": [
      {
        "id": "wanderlust-cuff-beanie-dark-grey-one-size",
        "variantId": "5360378913",
        "sku": "6A34C62D24CAA",
        "size": "One size",
        "color": "Dark Grey",
        "swatch": "#5b5f63",
        "inStock": true
      }
    ]
  },
  {
    "slug": "borealis-camp-mug",
    "name": "Borealis Camp Mug",
    "subtitle": "Accessories · made to order",
    "category": "accessories",
    "collection": "peaks",
    "price": 1650,
    "externalId": "440601843",
    "tagline": "Cold and free beats warm and bored.",
    "description": "Borealis Camp Mug — Cold and free beats warm and bored. Printed and embroidered to order, then shipped across Canada and the continent.",
    "details": [
      "Made to order — printed/embroidered on demand",
      "Ships across Canada & North America",
      "1 colourway · sizes 15 oz",
      "EVOLVE artwork — earned outside"
    ],
    "tone": [
      "#13233a",
      "#4ade80"
    ],
    "images": [
      "/products/p440601843-0.png"
    ],
    "sizes": [
      "15 oz"
    ],
    "variants": [
      {
        "id": "borealis-camp-mug-black-15-oz",
        "variantId": "5360367090",
        "sku": "6A34C10E6C765",
        "size": "15 oz",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      }
    ]
  },
  {
    "slug": "stealth-full-zip-hoodie",
    "name": "Stealth Full-Zip Hoodie",
    "subtitle": "Outerwear · made to order",
    "category": "outerwear",
    "collection": "prairies",
    "price": 5900,
    "externalId": "440600277",
    "tagline": "Where the signal dies, we come alive.",
    "description": "Stealth Full-Zip Hoodie — Where the signal dies, we come alive. Printed and embroidered to order, then shipped across Canada and the continent.",
    "details": [
      "Made to order — printed/embroidered on demand",
      "Ships across Canada & North America",
      "1 colourway · sizes S, M, L, XL, 2XL, 3XL",
      "EVOLVE artwork — earned outside"
    ],
    "tone": [
      "#3a2f12",
      "#39ff14"
    ],
    "images": [
      "/products/p440600277-0.png"
    ],
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL",
      "3XL"
    ],
    "variants": [
      {
        "id": "stealth-full-zip-hoodie-black-s",
        "variantId": "5360361034",
        "sku": "6A34BE729C6EC_S",
        "size": "S",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "stealth-full-zip-hoodie-black-m",
        "variantId": "5360361035",
        "sku": "6A34BE729C6EC_M",
        "size": "M",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "stealth-full-zip-hoodie-black-l",
        "variantId": "5360361036",
        "sku": "6A34BE729C6EC_L",
        "size": "L",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "stealth-full-zip-hoodie-black-xl",
        "variantId": "5360361037",
        "sku": "6A34BE729C6EC_XL",
        "size": "XL",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "stealth-full-zip-hoodie-black-2xl",
        "variantId": "5360361038",
        "sku": "6A34BE729C6EC_2XL",
        "size": "2XL",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "stealth-full-zip-hoodie-black-3xl",
        "variantId": "5360361039",
        "sku": "6A34BE729C6EC_3XL",
        "size": "3XL",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      }
    ]
  },
  {
    "slug": "hearth-fleece-zip",
    "name": "Hearth Fleece Zip",
    "subtitle": "Outerwear · made to order",
    "category": "outerwear",
    "collection": "coast",
    "price": 7550,
    "externalId": "440597762",
    "tagline": "Work hard. Play harder. Get outside.",
    "description": "Hearth Fleece Zip — Work hard. Play harder. Get outside. Printed and embroidered to order, then shipped across Canada and the continent.",
    "details": [
      "Made to order — printed/embroidered on demand",
      "Ships across Canada & North America",
      "1 colourway · sizes S, M, L, XL, 2XL",
      "EVOLVE artwork — earned outside"
    ],
    "tone": [
      "#0c2c33",
      "#00ff41"
    ],
    "images": [
      "/products/p440597762-0.png"
    ],
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "variants": [
      {
        "id": "hearth-fleece-zip-charcoal-heather-s",
        "variantId": "5360349581",
        "sku": "6A34BA4671867_S",
        "size": "S",
        "color": "Charcoal Heather",
        "swatch": "#8a9099",
        "inStock": true
      },
      {
        "id": "hearth-fleece-zip-charcoal-heather-m",
        "variantId": "5360349582",
        "sku": "6A34BA4671867_M",
        "size": "M",
        "color": "Charcoal Heather",
        "swatch": "#8a9099",
        "inStock": true
      },
      {
        "id": "hearth-fleece-zip-charcoal-heather-l",
        "variantId": "5360349583",
        "sku": "6A34BA4671867_L",
        "size": "L",
        "color": "Charcoal Heather",
        "swatch": "#8a9099",
        "inStock": true
      },
      {
        "id": "hearth-fleece-zip-charcoal-heather-xl",
        "variantId": "5360349584",
        "sku": "6A34BA4671867_XL",
        "size": "XL",
        "color": "Charcoal Heather",
        "swatch": "#8a9099",
        "inStock": true
      },
      {
        "id": "hearth-fleece-zip-charcoal-heather-2xl",
        "variantId": "5360349585",
        "sku": "6A34BA4671867_2XL",
        "size": "2XL",
        "color": "Charcoal Heather",
        "swatch": "#8a9099",
        "inStock": true
      }
    ]
  }
];
