// AUTO-GENERATED by scripts/sync-printful.mjs — do not edit by hand.
// Source: Printful "Evolve" store. Re-run the script to refresh.
import type { Product } from "./products";

export const PRINTFUL_PRODUCTS: Product[] = [
  {
    "slug": "camouflage-trucker-hat",
    "name": "Camouflage trucker hat",
    "subtitle": "Headwear · made to order",
    "category": "headwear",
    "collection": "boreal",
    "price": 3300,
    "externalId": "441089440",
    "tagline": "Descended from survivors.",
    "description": "Camouflage trucker hat — Descended from survivors. Printed and embroidered to order, then shipped across Canada and the continent.",
    "details": [
      "Made to order — printed/embroidered on demand",
      "Ships across Canada & North America",
      "1 colourway · sizes One size",
      "EVOLVE artwork — earned outside"
    ],
    "tone": [
      "#0d3b1f",
      "#00ff41"
    ],
    "images": [
      "/products/p441089440-0.png"
    ],
    "sizes": [
      "One size"
    ],
    "variants": [
      {
        "id": "camouflage-trucker-hat-camo-olive-one-size",
        "variantId": "5362675264",
        "sku": "6A377452C4E15",
        "size": "One size",
        "color": "Camo/Olive",
        "swatch": "#3d4a2b",
        "inStock": true
      }
    ]
  },
  {
    "slug": "unisex-hoodie",
    "name": "Unisex Hoodie",
    "subtitle": "Outerwear · made to order",
    "category": "outerwear",
    "collection": "peaks",
    "price": 5450,
    "externalId": "441089080",
    "tagline": "Built for the bush. Made for the long haul.",
    "description": "Unisex Hoodie — Built for the bush. Made for the long haul. Printed and embroidered to order, then shipped across Canada and the continent.",
    "details": [
      "Made to order — printed/embroidered on demand",
      "Ships across Canada & North America",
      "1 colourway · sizes S, M, L, XL, 2XL",
      "EVOLVE artwork — earned outside"
    ],
    "tone": [
      "#13233a",
      "#4ade80"
    ],
    "images": [
      "/products/p441089080-0.png"
    ],
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "variants": [
      {
        "id": "unisex-hoodie-carbon-grey-s",
        "variantId": "5362674524",
        "sku": "6A3773EE4302A_S",
        "size": "S",
        "color": "Carbon Grey",
        "swatch": "#44474a",
        "inStock": true
      },
      {
        "id": "unisex-hoodie-carbon-grey-m",
        "variantId": "5362674525",
        "sku": "6A3773EE4302A_M",
        "size": "M",
        "color": "Carbon Grey",
        "swatch": "#44474a",
        "inStock": true
      },
      {
        "id": "unisex-hoodie-carbon-grey-l",
        "variantId": "5362674526",
        "sku": "6A3773EE4302A_L",
        "size": "L",
        "color": "Carbon Grey",
        "swatch": "#44474a",
        "inStock": true
      },
      {
        "id": "unisex-hoodie-carbon-grey-xl",
        "variantId": "5362674527",
        "sku": "6A3773EE4302A_XL",
        "size": "XL",
        "color": "Carbon Grey",
        "swatch": "#44474a",
        "inStock": true
      },
      {
        "id": "unisex-hoodie-carbon-grey-2xl",
        "variantId": "5362674528",
        "sku": "6A3773EE4302A_2XL",
        "size": "2XL",
        "color": "Carbon Grey",
        "swatch": "#44474a",
        "inStock": true
      }
    ]
  },
  {
    "slug": "men-s-champion-long-sleeve-shirt",
    "name": "Men's Champion Long Sleeve Shirt",
    "subtitle": "Tops · made to order",
    "category": "tops",
    "collection": "prairies",
    "price": 4750,
    "externalId": "441087767",
    "tagline": "Earned outside.",
    "description": "Men's Champion Long Sleeve Shirt — Earned outside. Printed and embroidered to order, then shipped across Canada and the continent.",
    "details": [
      "Made to order — printed/embroidered on demand",
      "Ships across Canada & North America",
      "1 colourway · sizes S, M, L, XL, 2XL",
      "EVOLVE artwork — earned outside"
    ],
    "tone": [
      "#3a2f12",
      "#39ff14"
    ],
    "images": [
      "/products/p441087767-0.png"
    ],
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "variants": [
      {
        "id": "men-s-champion-long-sleeve-shirt-white-s",
        "variantId": "5362668206",
        "sku": "6A3771D05A41F_S",
        "size": "S",
        "color": "White",
        "swatch": "#ece9e2",
        "inStock": true
      },
      {
        "id": "men-s-champion-long-sleeve-shirt-white-m",
        "variantId": "5362668207",
        "sku": "6A3771D05A41F_M",
        "size": "M",
        "color": "White",
        "swatch": "#ece9e2",
        "inStock": true
      },
      {
        "id": "men-s-champion-long-sleeve-shirt-white-l",
        "variantId": "5362668208",
        "sku": "6A3771D05A41F_L",
        "size": "L",
        "color": "White",
        "swatch": "#ece9e2",
        "inStock": true
      },
      {
        "id": "men-s-champion-long-sleeve-shirt-white-xl",
        "variantId": "5362668209",
        "sku": "6A3771D05A41F_XL",
        "size": "XL",
        "color": "White",
        "swatch": "#ece9e2",
        "inStock": true
      },
      {
        "id": "men-s-champion-long-sleeve-shirt-white-2xl",
        "variantId": "5362668210",
        "sku": "6A3771D05A41F_2XL",
        "size": "2XL",
        "color": "White",
        "swatch": "#ece9e2",
        "inStock": true
      }
    ]
  },
  {
    "slug": "hooded-long-sleeve-tee",
    "name": "Hooded long-sleeve tee",
    "subtitle": "Tops · made to order",
    "category": "tops",
    "collection": "coast",
    "price": 4100,
    "externalId": "441087198",
    "tagline": "Canadian-built. Weather-tested.",
    "description": "Hooded long-sleeve tee — Canadian-built. Weather-tested. Printed and embroidered to order, then shipped across Canada and the continent.",
    "details": [
      "Made to order — printed/embroidered on demand",
      "Ships across Canada & North America",
      "1 colourway · sizes XS, S, M, L, XL, 2XL",
      "EVOLVE artwork — earned outside"
    ],
    "tone": [
      "#0c2c33",
      "#00ff41"
    ],
    "images": [
      "/products/p441087198-0.png"
    ],
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "variants": [
      {
        "id": "hooded-long-sleeve-tee-charcoal-black-triblend-xs",
        "variantId": "5362665594",
        "sku": "6A3770D5D397C_XS",
        "size": "XS",
        "color": "Charcoal-Black Triblend",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "hooded-long-sleeve-tee-charcoal-black-triblend-s",
        "variantId": "5362665595",
        "sku": "6A3770D5D397C_S",
        "size": "S",
        "color": "Charcoal-Black Triblend",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "hooded-long-sleeve-tee-charcoal-black-triblend-m",
        "variantId": "5362665597",
        "sku": "6A3770D5D397C_M",
        "size": "M",
        "color": "Charcoal-Black Triblend",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "hooded-long-sleeve-tee-charcoal-black-triblend-l",
        "variantId": "5362665598",
        "sku": "6A3770D5D397C_L",
        "size": "L",
        "color": "Charcoal-Black Triblend",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "hooded-long-sleeve-tee-charcoal-black-triblend-xl",
        "variantId": "5362665599",
        "sku": "6A3770D5D397C_XL",
        "size": "XL",
        "color": "Charcoal-Black Triblend",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "hooded-long-sleeve-tee-charcoal-black-triblend-2xl",
        "variantId": "5362665600",
        "sku": "6A3770D5D397C_2XL",
        "size": "2XL",
        "color": "Charcoal-Black Triblend",
        "swatch": "#0a0a0a",
        "inStock": true
      }
    ]
  },
  {
    "slug": "premium-full-zip-hoodie",
    "name": "Premium full zip hoodie",
    "subtitle": "Outerwear · made to order",
    "category": "outerwear",
    "collection": "boreal",
    "price": 5250,
    "externalId": "441085408",
    "tagline": "Strip it back. Build it stronger.",
    "description": "Premium full zip hoodie — Strip it back. Build it stronger. Printed and embroidered to order, then shipped across Canada and the continent.",
    "details": [
      "Made to order — printed/embroidered on demand",
      "Ships across Canada & North America",
      "1 colourway · sizes S, M, L, XL, 2XL, 3XL",
      "EVOLVE artwork — earned outside"
    ],
    "tone": [
      "#0d3b1f",
      "#00ff41"
    ],
    "images": [
      "/products/p441085408-0.png"
    ],
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL",
      "3XL"
    ],
    "variants": [
      {
        "id": "premium-full-zip-hoodie-charcoal-heather-s",
        "variantId": "5362657742",
        "sku": "6A376D492E307_S",
        "size": "S",
        "color": "Charcoal Heather",
        "swatch": "#8a9099",
        "inStock": true
      },
      {
        "id": "premium-full-zip-hoodie-charcoal-heather-m",
        "variantId": "5362657743",
        "sku": "6A376D492E307_M",
        "size": "M",
        "color": "Charcoal Heather",
        "swatch": "#8a9099",
        "inStock": true
      },
      {
        "id": "premium-full-zip-hoodie-charcoal-heather-l",
        "variantId": "5362657744",
        "sku": "6A376D492E307_L",
        "size": "L",
        "color": "Charcoal Heather",
        "swatch": "#8a9099",
        "inStock": true
      },
      {
        "id": "premium-full-zip-hoodie-charcoal-heather-xl",
        "variantId": "5362657745",
        "sku": "6A376D492E307_XL",
        "size": "XL",
        "color": "Charcoal Heather",
        "swatch": "#8a9099",
        "inStock": true
      },
      {
        "id": "premium-full-zip-hoodie-charcoal-heather-2xl",
        "variantId": "5362657746",
        "sku": "6A376D492E307_2XL",
        "size": "2XL",
        "color": "Charcoal Heather",
        "swatch": "#8a9099",
        "inStock": true
      },
      {
        "id": "premium-full-zip-hoodie-charcoal-heather-3xl",
        "variantId": "5362657747",
        "sku": "6A376D492E307_3XL",
        "size": "3XL",
        "color": "Charcoal Heather",
        "swatch": "#8a9099",
        "inStock": true
      }
    ],
    "badge": "Flagship"
  },
  {
    "slug": "evolve-unisex-classic-tee",
    "name": "Evolve Unisex classic tee",
    "subtitle": "Tops · made to order",
    "category": "tops",
    "collection": "peaks",
    "price": 1600,
    "externalId": "441085023",
    "tagline": "Cold and free beats warm and bored.",
    "description": "Evolve Unisex classic tee — Cold and free beats warm and bored. Printed and embroidered to order, then shipped across Canada and the continent.",
    "details": [
      "Made to order — printed/embroidered on demand",
      "Ships across Canada & North America",
      "1 colourway · sizes S, M, L, XL, 2XL, 3XL",
      "EVOLVE artwork — earned outside"
    ],
    "tone": [
      "#13233a",
      "#4ade80"
    ],
    "images": [
      "/products/p441085023-0.png"
    ],
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL",
      "3XL"
    ],
    "variants": [
      {
        "id": "evolve-unisex-classic-tee-natural-s",
        "variantId": "5362656022",
        "sku": "6A376C77437A5_S",
        "size": "S",
        "color": "Natural",
        "swatch": "#e6dcc6",
        "inStock": true
      },
      {
        "id": "evolve-unisex-classic-tee-natural-m",
        "variantId": "5362656023",
        "sku": "6A376C77437A5_M",
        "size": "M",
        "color": "Natural",
        "swatch": "#e6dcc6",
        "inStock": true
      },
      {
        "id": "evolve-unisex-classic-tee-natural-l",
        "variantId": "5362656024",
        "sku": "6A376C77437A5_L",
        "size": "L",
        "color": "Natural",
        "swatch": "#e6dcc6",
        "inStock": true
      },
      {
        "id": "evolve-unisex-classic-tee-natural-xl",
        "variantId": "5362656025",
        "sku": "6A376C77437A5_XL",
        "size": "XL",
        "color": "Natural",
        "swatch": "#e6dcc6",
        "inStock": true
      },
      {
        "id": "evolve-unisex-classic-tee-natural-2xl",
        "variantId": "5362656026",
        "sku": "6A376C77437A5_2XL",
        "size": "2XL",
        "color": "Natural",
        "swatch": "#e6dcc6",
        "inStock": true
      },
      {
        "id": "evolve-unisex-classic-tee-natural-3xl",
        "variantId": "5362656027",
        "sku": "6A376C77437A5_3XL",
        "size": "3XL",
        "color": "Natural",
        "swatch": "#e6dcc6",
        "inStock": true
      }
    ]
  },
  {
    "slug": "evolve-forrest-green-heavyweight-hooded-sweatshirt",
    "name": "Evolve Forrest Green Heavyweight Hooded Sweatshirt",
    "subtitle": "Outerwear · made to order",
    "category": "outerwear",
    "collection": "prairies",
    "price": 5800,
    "externalId": "441084646",
    "tagline": "Where the signal dies, we come alive.",
    "description": "Evolve Forrest Green Heavyweight Hooded Sweatshirt — Where the signal dies, we come alive. Printed and embroidered to order, then shipped across Canada and the continent.",
    "details": [
      "Made to order — printed/embroidered on demand",
      "Ships across Canada & North America",
      "1 colourway · sizes XS, S, M, L, XL, 2XL, 3XL",
      "EVOLVE artwork — earned outside"
    ],
    "tone": [
      "#3a2f12",
      "#39ff14"
    ],
    "images": [
      "/products/p441084646-0.png"
    ],
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "2XL",
      "3XL"
    ],
    "variants": [
      {
        "id": "evolve-forrest-green-heavyweight-hooded-sweatshirt-army-xs",
        "variantId": "5362654378",
        "sku": "6A376BCE469F2_XS",
        "size": "XS",
        "color": "Army",
        "swatch": "#4b5320",
        "inStock": true
      },
      {
        "id": "evolve-forrest-green-heavyweight-hooded-sweatshirt-army-s",
        "variantId": "5362654379",
        "sku": "6A376BCE469F2_S",
        "size": "S",
        "color": "Army",
        "swatch": "#4b5320",
        "inStock": true
      },
      {
        "id": "evolve-forrest-green-heavyweight-hooded-sweatshirt-army-m",
        "variantId": "5362654380",
        "sku": "6A376BCE469F2_M",
        "size": "M",
        "color": "Army",
        "swatch": "#4b5320",
        "inStock": true
      },
      {
        "id": "evolve-forrest-green-heavyweight-hooded-sweatshirt-army-l",
        "variantId": "5362654381",
        "sku": "6A376BCE469F2_L",
        "size": "L",
        "color": "Army",
        "swatch": "#4b5320",
        "inStock": true
      },
      {
        "id": "evolve-forrest-green-heavyweight-hooded-sweatshirt-army-xl",
        "variantId": "5362654382",
        "sku": "6A376BCE469F2_XL",
        "size": "XL",
        "color": "Army",
        "swatch": "#4b5320",
        "inStock": true
      },
      {
        "id": "evolve-forrest-green-heavyweight-hooded-sweatshirt-army-2xl",
        "variantId": "5362654383",
        "sku": "6A376BCE469F2_2XL",
        "size": "2XL",
        "color": "Army",
        "swatch": "#4b5320",
        "inStock": true
      },
      {
        "id": "evolve-forrest-green-heavyweight-hooded-sweatshirt-army-3xl",
        "variantId": "5362654384",
        "sku": "6A376BCE469F2_3XL",
        "size": "3XL",
        "color": "Army",
        "swatch": "#4b5320",
        "inStock": true
      }
    ]
  },
  {
    "slug": "snapback-hat",
    "name": "Snapback Hat",
    "subtitle": "Headwear · made to order",
    "category": "headwear",
    "collection": "coast",
    "price": 3150,
    "externalId": "441084360",
    "tagline": "Work hard. Play harder. Get outside.",
    "description": "Snapback Hat — Work hard. Play harder. Get outside. Printed and embroidered to order, then shipped across Canada and the continent.",
    "details": [
      "Made to order — printed/embroidered on demand",
      "Ships across Canada & North America",
      "1 colourway · sizes One size",
      "EVOLVE artwork — earned outside"
    ],
    "tone": [
      "#0c2c33",
      "#00ff41"
    ],
    "images": [
      "/products/p441084360-0.png"
    ],
    "sizes": [
      "One size"
    ],
    "variants": [
      {
        "id": "snapback-hat-heather-grey-one-size",
        "variantId": "5362652623",
        "sku": "6A376B3FB75A3",
        "size": "One size",
        "color": "Heather Grey",
        "swatch": "#8a9099",
        "inStock": true
      }
    ]
  },
  {
    "slug": "evolve-organic-white-on-black",
    "name": "Evolve Organic White on Black",
    "subtitle": "Tops · made to order",
    "category": "tops",
    "collection": "boreal",
    "price": 3550,
    "externalId": "441084054",
    "tagline": "Restore what the week wore down.",
    "description": "Evolve Organic White on Black — Restore what the week wore down. Printed and embroidered to order, then shipped across Canada and the continent.",
    "details": [
      "Made to order — printed/embroidered on demand",
      "Ships across Canada & North America",
      "1 colourway · sizes One size",
      "EVOLVE artwork — earned outside"
    ],
    "tone": [
      "#0d3b1f",
      "#00ff41"
    ],
    "images": [
      "/products/p441084054-0.png"
    ],
    "sizes": [
      "One size"
    ],
    "variants": [
      {
        "id": "evolve-organic-white-on-black-black-one-size",
        "variantId": "5362651251",
        "sku": "6A376AB07E34E",
        "size": "One size",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      }
    ]
  },
  {
    "slug": "snapback-hat-3649",
    "name": "Snapback Hat",
    "subtitle": "Headwear · made to order",
    "category": "headwear",
    "collection": "peaks",
    "price": 3100,
    "externalId": "441083649",
    "tagline": "Tougher than the winters that made us.",
    "description": "Snapback Hat — Tougher than the winters that made us. Printed and embroidered to order, then shipped across Canada and the continent.",
    "details": [
      "Made to order — printed/embroidered on demand",
      "Ships across Canada & North America",
      "1 colourway · sizes One size",
      "EVOLVE artwork — earned outside"
    ],
    "tone": [
      "#13233a",
      "#4ade80"
    ],
    "images": [
      "/products/p441083649-0.png"
    ],
    "sizes": [
      "One size"
    ],
    "variants": [
      {
        "id": "snapback-hat-3649-dark-grey-one-size",
        "variantId": "5362649362",
        "sku": "6A376A2850E8E",
        "size": "One size",
        "color": "Dark Grey",
        "swatch": "#5b5f63",
        "inStock": true
      }
    ]
  },
  {
    "slug": "embroidered-champion-packable-jacket",
    "name": "Embroidered Champion Packable Jacket",
    "subtitle": "Outerwear · made to order",
    "category": "outerwear",
    "collection": "prairies",
    "price": 7800,
    "externalId": "441082795",
    "tagline": "From the wheat to the water.",
    "description": "Embroidered Champion Packable Jacket — From the wheat to the water. Printed and embroidered to order, then shipped across Canada and the continent.",
    "details": [
      "Made to order — printed/embroidered on demand",
      "Ships across Canada & North America",
      "1 colourway · sizes S",
      "EVOLVE artwork — earned outside"
    ],
    "tone": [
      "#3a2f12",
      "#39ff14"
    ],
    "images": [
      "/products/p441082795-0.png"
    ],
    "sizes": [
      "S"
    ],
    "variants": [
      {
        "id": "embroidered-champion-packable-jacket-black-s",
        "variantId": "5362646673",
        "sku": "6A37692B2230C",
        "size": "S",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      }
    ]
  },
  {
    "slug": "trucker-cap",
    "name": "Trucker Cap",
    "subtitle": "Headwear · made to order",
    "category": "headwear",
    "collection": "coast",
    "price": 3250,
    "externalId": "441082547",
    "tagline": "Some things should never change. Get outside.",
    "description": "Trucker Cap — Some things should never change. Get outside. Printed and embroidered to order, then shipped across Canada and the continent.",
    "details": [
      "Made to order — printed/embroidered on demand",
      "Ships across Canada & North America",
      "1 colourway · sizes One size",
      "EVOLVE artwork — earned outside"
    ],
    "tone": [
      "#0c2c33",
      "#00ff41"
    ],
    "images": [
      "/products/p441082547-0.png"
    ],
    "sizes": [
      "One size"
    ],
    "variants": [
      {
        "id": "trucker-cap-loden-one-size",
        "variantId": "5362645425",
        "sku": "6A3768A50899B",
        "size": "One size",
        "color": "Loden",
        "swatch": "#3d4a2b",
        "inStock": true
      }
    ]
  },
  {
    "slug": "unisex-ringer-t-shirt",
    "name": "Unisex ringer t-shirt",
    "subtitle": "Tops · made to order",
    "category": "tops",
    "collection": "boreal",
    "price": 2650,
    "externalId": "441082269",
    "tagline": "Descended from survivors.",
    "description": "Unisex ringer t-shirt — Descended from survivors. Printed and embroidered to order, then shipped across Canada and the continent.",
    "details": [
      "Made to order — printed/embroidered on demand",
      "Ships across Canada & North America",
      "1 colourway · sizes S, M, L, XL, 2XL, 3XL",
      "EVOLVE artwork — earned outside"
    ],
    "tone": [
      "#0d3b1f",
      "#00ff41"
    ],
    "images": [
      "/products/p441082269-0.png"
    ],
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL",
      "3XL"
    ],
    "variants": [
      {
        "id": "unisex-ringer-t-shirt-heather-gray-black-s",
        "variantId": "5362644524",
        "sku": "6A37683C61B53_S",
        "size": "S",
        "color": "Heather Gray / Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "unisex-ringer-t-shirt-heather-gray-black-m",
        "variantId": "5362644525",
        "sku": "6A37683C61B53_M",
        "size": "M",
        "color": "Heather Gray / Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "unisex-ringer-t-shirt-heather-gray-black-l",
        "variantId": "5362644526",
        "sku": "6A37683C61B53_L",
        "size": "L",
        "color": "Heather Gray / Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "unisex-ringer-t-shirt-heather-gray-black-xl",
        "variantId": "5362644527",
        "sku": "6A37683C61B53_XL",
        "size": "XL",
        "color": "Heather Gray / Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "unisex-ringer-t-shirt-heather-gray-black-2xl",
        "variantId": "5362644528",
        "sku": "6A37683C61B53_2XL",
        "size": "2XL",
        "color": "Heather Gray / Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "unisex-ringer-t-shirt-heather-gray-black-3xl",
        "variantId": "5362644529",
        "sku": "6A37683C61B53_3XL",
        "size": "3XL",
        "color": "Heather Gray / Black",
        "swatch": "#0a0a0a",
        "inStock": true
      }
    ]
  },
  {
    "slug": "evolve-embroidered-organic-t",
    "name": "Evolve Embroidered organic t",
    "subtitle": "Tops · made to order",
    "category": "tops",
    "collection": "peaks",
    "price": 3000,
    "externalId": "440709618",
    "tagline": "Built for the bush. Made for the long haul.",
    "description": "Evolve Embroidered organic t — Built for the bush. Made for the long haul. Printed and embroidered to order, then shipped across Canada and the continent.",
    "details": [
      "Made to order — printed/embroidered on demand",
      "Ships across Canada & North America",
      "1 colourway · sizes S, M, L, XL, 2XL",
      "EVOLVE artwork — earned outside"
    ],
    "tone": [
      "#13233a",
      "#4ade80"
    ],
    "images": [
      "/products/p440709618-0.png"
    ],
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "variants": [
      {
        "id": "evolve-embroidered-organic-t-desert-dust-s",
        "variantId": "5360918931",
        "sku": "6A355A69CEBF3_S",
        "size": "S",
        "color": "Desert Dust",
        "swatch": "#3d4a2b",
        "inStock": true
      },
      {
        "id": "evolve-embroidered-organic-t-desert-dust-m",
        "variantId": "5360918932",
        "sku": "6A355A69CEBF3_M",
        "size": "M",
        "color": "Desert Dust",
        "swatch": "#3d4a2b",
        "inStock": true
      },
      {
        "id": "evolve-embroidered-organic-t-desert-dust-l",
        "variantId": "5360918933",
        "sku": "6A355A69CEBF3_L",
        "size": "L",
        "color": "Desert Dust",
        "swatch": "#3d4a2b",
        "inStock": true
      },
      {
        "id": "evolve-embroidered-organic-t-desert-dust-xl",
        "variantId": "5360918934",
        "sku": "6A355A69CEBF3_XL",
        "size": "XL",
        "color": "Desert Dust",
        "swatch": "#3d4a2b",
        "inStock": true
      },
      {
        "id": "evolve-embroidered-organic-t-desert-dust-2xl",
        "variantId": "5360918935",
        "sku": "6A355A69CEBF3_2XL",
        "size": "2XL",
        "color": "Desert Dust",
        "swatch": "#3d4a2b",
        "inStock": true
      }
    ]
  },
  {
    "slug": "evolve-tank",
    "name": "Evolve Tank",
    "subtitle": "Tops · made to order",
    "category": "tops",
    "collection": "prairies",
    "price": 2550,
    "externalId": "440708831",
    "tagline": "Earned outside.",
    "description": "Evolve Tank — Earned outside. Printed and embroidered to order, then shipped across Canada and the continent.",
    "details": [
      "Made to order — printed/embroidered on demand",
      "Ships across Canada & North America",
      "1 colourway · sizes XS, S, M, L, XL, 2XL",
      "EVOLVE artwork — earned outside"
    ],
    "tone": [
      "#3a2f12",
      "#39ff14"
    ],
    "images": [
      "/products/p440708831-0.png"
    ],
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "variants": [
      {
        "id": "evolve-tank-black-xs",
        "variantId": "5360914569",
        "sku": "6A35595A57F56_XS",
        "size": "XS",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "evolve-tank-black-s",
        "variantId": "5360914570",
        "sku": "6A35595A57F56_S",
        "size": "S",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "evolve-tank-black-m",
        "variantId": "5360914571",
        "sku": "6A35595A57F56_M",
        "size": "M",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "evolve-tank-black-l",
        "variantId": "5360914572",
        "sku": "6A35595A57F56_L",
        "size": "L",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "evolve-tank-black-xl",
        "variantId": "5360914573",
        "sku": "6A35595A57F56_XL",
        "size": "XL",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "evolve-tank-black-2xl",
        "variantId": "5360914574",
        "sku": "6A35595A57F56_2XL",
        "size": "2XL",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      }
    ]
  },
  {
    "slug": "white-forest-snapback",
    "name": "White Forest Snapback",
    "subtitle": "Headwear · made to order",
    "category": "headwear",
    "collection": "coast",
    "price": 3100,
    "externalId": "440708024",
    "tagline": "Canadian-built. Weather-tested.",
    "description": "White Forest Snapback — Canadian-built. Weather-tested. Printed and embroidered to order, then shipped across Canada and the continent.",
    "details": [
      "Made to order — printed/embroidered on demand",
      "Ships across Canada & North America",
      "1 colourway · sizes One size",
      "EVOLVE artwork — earned outside"
    ],
    "tone": [
      "#0c2c33",
      "#00ff41"
    ],
    "images": [
      "/products/p440708024-0.png"
    ],
    "sizes": [
      "One size"
    ],
    "variants": [
      {
        "id": "white-forest-snapback-white-one-size",
        "variantId": "5360909429",
        "sku": "6A35586B4F8CE",
        "size": "One size",
        "color": "White",
        "swatch": "#ece9e2",
        "inStock": true
      }
    ]
  },
  {
    "slug": "trucker-cap-3219",
    "name": "Trucker Cap",
    "subtitle": "Headwear · made to order",
    "category": "headwear",
    "collection": "boreal",
    "price": 3250,
    "externalId": "440613219",
    "tagline": "Strip it back. Build it stronger.",
    "description": "Trucker Cap — Strip it back. Build it stronger. Printed and embroidered to order, then shipped across Canada and the continent.",
    "details": [
      "Made to order — printed/embroidered on demand",
      "Ships across Canada & North America",
      "1 colourway · sizes One size",
      "EVOLVE artwork — earned outside"
    ],
    "tone": [
      "#0d3b1f",
      "#00ff41"
    ],
    "images": [
      "/products/p440613219-0.png"
    ],
    "sizes": [
      "One size"
    ],
    "variants": [
      {
        "id": "trucker-cap-3219-loden-one-size",
        "variantId": "5360410273",
        "sku": "6A34D27D2548B",
        "size": "One size",
        "color": "Loden",
        "swatch": "#3d4a2b",
        "inStock": true
      }
    ]
  },
  {
    "slug": "evolve-hoodie",
    "name": "Evolve Hoodie",
    "subtitle": "Outerwear · made to order",
    "category": "outerwear",
    "collection": "peaks",
    "price": 4600,
    "externalId": "440612780",
    "tagline": "Cold and free beats warm and bored.",
    "description": "Evolve Hoodie — Cold and free beats warm and bored. Printed and embroidered to order, then shipped across Canada and the continent.",
    "details": [
      "Made to order — printed/embroidered on demand",
      "Ships across Canada & North America",
      "1 colourway · sizes S, M, L, XL, 2XL",
      "EVOLVE artwork — earned outside"
    ],
    "tone": [
      "#13233a",
      "#4ade80"
    ],
    "images": [
      "/products/p440612780-0.png"
    ],
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "variants": [
      {
        "id": "evolve-hoodie-black-s",
        "variantId": "5360409149",
        "sku": "6A34D1EBCC7D8_S",
        "size": "S",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "evolve-hoodie-black-m",
        "variantId": "5360409150",
        "sku": "6A34D1EBCC7D8_M",
        "size": "M",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "evolve-hoodie-black-l",
        "variantId": "5360409152",
        "sku": "6A34D1EBCC7D8_L",
        "size": "L",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "evolve-hoodie-black-xl",
        "variantId": "5360409153",
        "sku": "6A34D1EBCC7D8_XL",
        "size": "XL",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "evolve-hoodie-black-2xl",
        "variantId": "5360409154",
        "sku": "6A34D1EBCC7D8_2XL",
        "size": "2XL",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      }
    ]
  },
  {
    "slug": "evolve-white-on-black-v-neck",
    "name": "Evolve White on Black V-Neck",
    "subtitle": "Tops · made to order",
    "category": "tops",
    "collection": "prairies",
    "price": 3100,
    "externalId": "440612001",
    "tagline": "Where the signal dies, we come alive.",
    "description": "Evolve White on Black V-Neck — Where the signal dies, we come alive. Printed and embroidered to order, then shipped across Canada and the continent.",
    "details": [
      "Made to order — printed/embroidered on demand",
      "Ships across Canada & North America",
      "1 colourway · sizes S, M, L, XL, 2XL",
      "EVOLVE artwork — earned outside"
    ],
    "tone": [
      "#3a2f12",
      "#39ff14"
    ],
    "images": [
      "/products/p440612001-0.png"
    ],
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "variants": [
      {
        "id": "evolve-white-on-black-v-neck-black-s",
        "variantId": "5360406226",
        "sku": "6A34D0C8B3190_S",
        "size": "S",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "evolve-white-on-black-v-neck-black-m",
        "variantId": "5360406227",
        "sku": "6A34D0C8B3190_M",
        "size": "M",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "evolve-white-on-black-v-neck-black-l",
        "variantId": "5360406228",
        "sku": "6A34D0C8B3190_L",
        "size": "L",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "evolve-white-on-black-v-neck-black-xl",
        "variantId": "5360406229",
        "sku": "6A34D0C8B3190_XL",
        "size": "XL",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "evolve-white-on-black-v-neck-black-2xl",
        "variantId": "5360406230",
        "sku": "6A34D0C8B3190_2XL",
        "size": "2XL",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      }
    ]
  },
  {
    "slug": "evolve-premium-sweatshirt",
    "name": "Evolve Premium Sweatshirt",
    "subtitle": "Outerwear · made to order",
    "category": "outerwear",
    "collection": "coast",
    "price": 4050,
    "externalId": "440610853",
    "tagline": "Work hard. Play harder. Get outside.",
    "description": "Evolve Premium Sweatshirt — Work hard. Play harder. Get outside. Printed and embroidered to order, then shipped across Canada and the continent.",
    "details": [
      "Made to order — printed/embroidered on demand",
      "Ships across Canada & North America",
      "1 colourway · sizes S, M, L, XL, 2XL",
      "EVOLVE artwork — earned outside"
    ],
    "tone": [
      "#0c2c33",
      "#00ff41"
    ],
    "images": [
      "/products/p440610853-0.png"
    ],
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "variants": [
      {
        "id": "evolve-premium-sweatshirt-black-s",
        "variantId": "5360402035",
        "sku": "6A34CF011E23B_S",
        "size": "S",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "evolve-premium-sweatshirt-black-m",
        "variantId": "5360402036",
        "sku": "6A34CF011E23B_M",
        "size": "M",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "evolve-premium-sweatshirt-black-l",
        "variantId": "5360402037",
        "sku": "6A34CF011E23B_L",
        "size": "L",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "evolve-premium-sweatshirt-black-xl",
        "variantId": "5360402038",
        "sku": "6A34CF011E23B_XL",
        "size": "XL",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "evolve-premium-sweatshirt-black-2xl",
        "variantId": "5360402039",
        "sku": "6A34CF011E23B_2XL",
        "size": "2XL",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      }
    ]
  },
  {
    "slug": "evolve-dark-on-dark-hoodie",
    "name": "Evolve Dark on Dark Hoodie",
    "subtitle": "Outerwear · made to order",
    "category": "outerwear",
    "collection": "boreal",
    "price": 3550,
    "externalId": "440610516",
    "tagline": "Restore what the week wore down.",
    "description": "Evolve Dark on Dark Hoodie — Restore what the week wore down. Printed and embroidered to order, then shipped across Canada and the continent.",
    "details": [
      "Made to order — printed/embroidered on demand",
      "Ships across Canada & North America",
      "1 colourway · sizes S, M, L, XL, 2XL",
      "EVOLVE artwork — earned outside"
    ],
    "tone": [
      "#0d3b1f",
      "#00ff41"
    ],
    "images": [
      "/products/p440610516-0.png"
    ],
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "variants": [
      {
        "id": "evolve-dark-on-dark-hoodie-black-s",
        "variantId": "5360401045",
        "sku": "6A34CE59C1E53_S",
        "size": "S",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "evolve-dark-on-dark-hoodie-black-m",
        "variantId": "5360401046",
        "sku": "6A34CE59C1E53_M",
        "size": "M",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "evolve-dark-on-dark-hoodie-black-l",
        "variantId": "5360401047",
        "sku": "6A34CE59C1E53_L",
        "size": "L",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "evolve-dark-on-dark-hoodie-black-xl",
        "variantId": "5360401048",
        "sku": "6A34CE59C1E53_XL",
        "size": "XL",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "evolve-dark-on-dark-hoodie-black-2xl",
        "variantId": "5360401049",
        "sku": "6A34CE59C1E53_2XL",
        "size": "2XL",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      }
    ],
    "badge": "Flagship"
  },
  {
    "slug": "evolve-premium-heavyweight-tee",
    "name": "Evolve premium heavyweight tee",
    "subtitle": "Tops · made to order",
    "category": "tops",
    "collection": "peaks",
    "price": 2550,
    "externalId": "440609882",
    "tagline": "Tougher than the winters that made us.",
    "description": "Evolve premium heavyweight tee — Tougher than the winters that made us. Printed and embroidered to order, then shipped across Canada and the continent.",
    "details": [
      "Made to order — printed/embroidered on demand",
      "Ships across Canada & North America",
      "1 colourway · sizes S, M, L, XL, 2XL",
      "EVOLVE artwork — earned outside"
    ],
    "tone": [
      "#13233a",
      "#4ade80"
    ],
    "images": [
      "/products/p440609882-0.png"
    ],
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "variants": [
      {
        "id": "evolve-premium-heavyweight-tee-black-s",
        "variantId": "5360399047",
        "sku": "6A34CD39B4E5B_S",
        "size": "S",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "evolve-premium-heavyweight-tee-black-m",
        "variantId": "5360399048",
        "sku": "6A34CD39B4E5B_M",
        "size": "M",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "evolve-premium-heavyweight-tee-black-l",
        "variantId": "5360399049",
        "sku": "6A34CD39B4E5B_L",
        "size": "L",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "evolve-premium-heavyweight-tee-black-xl",
        "variantId": "5360399050",
        "sku": "6A34CD39B4E5B_XL",
        "size": "XL",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "evolve-premium-heavyweight-tee-black-2xl",
        "variantId": "5360399051",
        "sku": "6A34CD39B4E5B_2XL",
        "size": "2XL",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      }
    ]
  },
  {
    "slug": "evolve-hunting-hoodie",
    "name": "Evolve Hunting Hoodie",
    "subtitle": "Outerwear · made to order",
    "category": "outerwear",
    "collection": "prairies",
    "price": 8650,
    "externalId": "440609698",
    "tagline": "From the wheat to the water.",
    "description": "Evolve Hunting Hoodie — From the wheat to the water. Printed and embroidered to order, then shipped across Canada and the continent.",
    "details": [
      "Made to order — printed/embroidered on demand",
      "Ships across Canada & North America",
      "1 colourway · sizes S, M, L, XL, 2XL",
      "EVOLVE artwork — earned outside"
    ],
    "tone": [
      "#3a2f12",
      "#39ff14"
    ],
    "images": [
      "/products/p440609698-0.png"
    ],
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "variants": [
      {
        "id": "evolve-hunting-hoodie-black-s",
        "variantId": "5360398514",
        "sku": "6A34CCF0BD407_S",
        "size": "S",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "evolve-hunting-hoodie-black-m",
        "variantId": "5360398515",
        "sku": "6A34CCF0BD407_M",
        "size": "M",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "evolve-hunting-hoodie-black-l",
        "variantId": "5360398516",
        "sku": "6A34CCF0BD407_L",
        "size": "L",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "evolve-hunting-hoodie-black-xl",
        "variantId": "5360398517",
        "sku": "6A34CCF0BD407_XL",
        "size": "XL",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "evolve-hunting-hoodie-black-2xl",
        "variantId": "5360398518",
        "sku": "6A34CCF0BD407_2XL",
        "size": "2XL",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      }
    ]
  },
  {
    "slug": "evolved-2-4-sleeve",
    "name": "Evolved 2/4 sleeve",
    "subtitle": "Tops · made to order",
    "category": "tops",
    "collection": "coast",
    "price": 3100,
    "externalId": "440609155",
    "tagline": "Some things should never change. Get outside.",
    "description": "Evolved 2/4 sleeve — Some things should never change. Get outside. Printed and embroidered to order, then shipped across Canada and the continent.",
    "details": [
      "Made to order — printed/embroidered on demand",
      "Ships across Canada & North America",
      "1 colourway · sizes XS, S, M, L, XL, 2XL",
      "EVOLVE artwork — earned outside"
    ],
    "tone": [
      "#0c2c33",
      "#00ff41"
    ],
    "images": [
      "/products/p440609155-0.png"
    ],
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "variants": [
      {
        "id": "evolved-2-4-sleeve-heather-denim-navy-xs",
        "variantId": "5360396891",
        "sku": "6A34CC2450ED2_XS",
        "size": "XS",
        "color": "Heather Denim/Navy",
        "swatch": "#1f2a3d",
        "inStock": true
      },
      {
        "id": "evolved-2-4-sleeve-heather-denim-navy-s",
        "variantId": "5360396892",
        "sku": "6A34CC2450ED2_S",
        "size": "S",
        "color": "Heather Denim/Navy",
        "swatch": "#1f2a3d",
        "inStock": true
      },
      {
        "id": "evolved-2-4-sleeve-heather-denim-navy-m",
        "variantId": "5360396893",
        "sku": "6A34CC2450ED2_M",
        "size": "M",
        "color": "Heather Denim/Navy",
        "swatch": "#1f2a3d",
        "inStock": true
      },
      {
        "id": "evolved-2-4-sleeve-heather-denim-navy-l",
        "variantId": "5360396894",
        "sku": "6A34CC2450ED2_L",
        "size": "L",
        "color": "Heather Denim/Navy",
        "swatch": "#1f2a3d",
        "inStock": true
      },
      {
        "id": "evolved-2-4-sleeve-heather-denim-navy-xl",
        "variantId": "5360396895",
        "sku": "6A34CC2450ED2_XL",
        "size": "XL",
        "color": "Heather Denim/Navy",
        "swatch": "#1f2a3d",
        "inStock": true
      },
      {
        "id": "evolved-2-4-sleeve-heather-denim-navy-2xl",
        "variantId": "5360396896",
        "sku": "6A34CC2450ED2_2XL",
        "size": "2XL",
        "color": "Heather Denim/Navy",
        "swatch": "#1f2a3d",
        "inStock": true
      }
    ]
  },
  {
    "slug": "evolved-print-v-neck-t-shirt",
    "name": "Evolved Print V-Neck T-Shirt",
    "subtitle": "Tops · made to order",
    "category": "tops",
    "collection": "boreal",
    "price": 3100,
    "externalId": "440608834",
    "tagline": "Descended from survivors.",
    "description": "Evolved Print V-Neck T-Shirt — Descended from survivors. Printed and embroidered to order, then shipped across Canada and the continent.",
    "details": [
      "Made to order — printed/embroidered on demand",
      "Ships across Canada & North America",
      "1 colourway · sizes XS, S, M, L, XL, 2XL",
      "EVOLVE artwork — earned outside"
    ],
    "tone": [
      "#0d3b1f",
      "#00ff41"
    ],
    "images": [
      "/products/p440608834-0.png"
    ],
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "variants": [
      {
        "id": "evolved-print-v-neck-t-shirt-dark-grey-heather-xs",
        "variantId": "5360395777",
        "sku": "6A34CB91E1988_XS",
        "size": "XS",
        "color": "Dark Grey Heather",
        "swatch": "#3a3d41",
        "inStock": true
      },
      {
        "id": "evolved-print-v-neck-t-shirt-dark-grey-heather-s",
        "variantId": "5360395778",
        "sku": "6A34CB91E1988_S",
        "size": "S",
        "color": "Dark Grey Heather",
        "swatch": "#3a3d41",
        "inStock": true
      },
      {
        "id": "evolved-print-v-neck-t-shirt-dark-grey-heather-m",
        "variantId": "5360395779",
        "sku": "6A34CB91E1988_M",
        "size": "M",
        "color": "Dark Grey Heather",
        "swatch": "#3a3d41",
        "inStock": true
      },
      {
        "id": "evolved-print-v-neck-t-shirt-dark-grey-heather-l",
        "variantId": "5360395780",
        "sku": "6A34CB91E1988_L",
        "size": "L",
        "color": "Dark Grey Heather",
        "swatch": "#3a3d41",
        "inStock": true
      },
      {
        "id": "evolved-print-v-neck-t-shirt-dark-grey-heather-xl",
        "variantId": "5360395781",
        "sku": "6A34CB91E1988_XL",
        "size": "XL",
        "color": "Dark Grey Heather",
        "swatch": "#3a3d41",
        "inStock": true
      },
      {
        "id": "evolved-print-v-neck-t-shirt-dark-grey-heather-2xl",
        "variantId": "5360395782",
        "sku": "6A34CB91E1988_2XL",
        "size": "2XL",
        "color": "Dark Grey Heather",
        "swatch": "#3a3d41",
        "inStock": true
      }
    ]
  },
  {
    "slug": "great-white-north-evolve-stainless-steel-tumbler",
    "name": "Great White North Evolve Stainless steel tumbler",
    "subtitle": "Accessories · made to order",
    "category": "accessories",
    "collection": "peaks",
    "price": 3900,
    "externalId": "440607891",
    "tagline": "Built for the bush. Made for the long haul.",
    "description": "Great White North Evolve Stainless steel tumbler — Built for the bush. Made for the long haul. Printed and embroidered to order, then shipped across Canada and the continent.",
    "details": [
      "Made to order — printed/embroidered on demand",
      "Ships across Canada & North America",
      "1 colourway · sizes 20 oz",
      "EVOLVE artwork — earned outside"
    ],
    "tone": [
      "#13233a",
      "#4ade80"
    ],
    "images": [
      "/products/p440607891-0.png"
    ],
    "sizes": [
      "20 oz"
    ],
    "variants": [
      {
        "id": "great-white-north-evolve-stainless-steel-tumbler-white-20-oz",
        "variantId": "5360390873",
        "sku": "6A34CA51549E9",
        "size": "20 oz",
        "color": "White",
        "swatch": "#ece9e2",
        "inStock": true
      }
    ]
  },
  {
    "slug": "evolve-original-stealth-snapback",
    "name": "Evolve Original Stealth Snapback",
    "subtitle": "Headwear · made to order",
    "category": "headwear",
    "collection": "prairies",
    "price": 3000,
    "externalId": "440607292",
    "tagline": "Earned outside.",
    "description": "Evolve Original Stealth Snapback — Earned outside. Printed and embroidered to order, then shipped across Canada and the continent.",
    "details": [
      "Made to order — printed/embroidered on demand",
      "Ships across Canada & North America",
      "1 colourway · sizes One size",
      "EVOLVE artwork — earned outside"
    ],
    "tone": [
      "#3a2f12",
      "#39ff14"
    ],
    "images": [
      "/products/p440607292-0.png"
    ],
    "sizes": [
      "One size"
    ],
    "variants": [
      {
        "id": "evolve-original-stealth-snapback-black-one-size",
        "variantId": "5360389107",
        "sku": "6A34C960682A9",
        "size": "One size",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      }
    ]
  },
  {
    "slug": "evolved-stealth-denim-baseball-cap",
    "name": "Evolved Stealth Denim Baseball Cap",
    "subtitle": "Headwear · made to order",
    "category": "headwear",
    "collection": "coast",
    "price": 2550,
    "externalId": "440606458",
    "tagline": "Canadian-built. Weather-tested.",
    "description": "Evolved Stealth Denim Baseball Cap — Canadian-built. Weather-tested. Printed and embroidered to order, then shipped across Canada and the continent.",
    "details": [
      "Made to order — printed/embroidered on demand",
      "Ships across Canada & North America",
      "1 colourway · sizes One size",
      "EVOLVE artwork — earned outside"
    ],
    "tone": [
      "#0c2c33",
      "#00ff41"
    ],
    "images": [
      "/products/p440606458-0.png"
    ],
    "sizes": [
      "One size"
    ],
    "variants": [
      {
        "id": "evolved-stealth-denim-baseball-cap-black-one-size",
        "variantId": "5360386477",
        "sku": "6A34C8166FAF9",
        "size": "One size",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      }
    ]
  },
  {
    "slug": "white-wanderlust-beanie",
    "name": "White Wanderlust Beanie",
    "subtitle": "Headwear · made to order",
    "category": "headwear",
    "collection": "boreal",
    "price": 2450,
    "externalId": "440605056",
    "tagline": "Strip it back. Build it stronger.",
    "description": "White Wanderlust Beanie — Strip it back. Build it stronger. Printed and embroidered to order, then shipped across Canada and the continent.",
    "details": [
      "Made to order — printed/embroidered on demand",
      "Ships across Canada & North America",
      "1 colourway · sizes One size",
      "EVOLVE artwork — earned outside"
    ],
    "tone": [
      "#0d3b1f",
      "#00ff41"
    ],
    "images": [
      "/products/p440605056-0.png"
    ],
    "sizes": [
      "One size"
    ],
    "variants": [
      {
        "id": "white-wanderlust-beanie-dark-grey-one-size",
        "variantId": "5360378913",
        "sku": "6A34C62D24CAA",
        "size": "One size",
        "color": "Dark Grey",
        "swatch": "#5b5f63",
        "inStock": true
      }
    ]
  },
  {
    "slug": "evolve-borealis-black-mug",
    "name": "Evolve Borealis Black Mug",
    "subtitle": "Accessories · made to order",
    "category": "accessories",
    "collection": "peaks",
    "price": 1650,
    "externalId": "440601843",
    "tagline": "Cold and free beats warm and bored.",
    "description": "Evolve Borealis Black Mug — Cold and free beats warm and bored. Printed and embroidered to order, then shipped across Canada and the continent.",
    "details": [
      "Made to order — printed/embroidered on demand",
      "Ships across Canada & North America",
      "1 colourway · sizes 15 oz",
      "EVOLVE artwork — earned outside"
    ],
    "tone": [
      "#13233a",
      "#4ade80"
    ],
    "images": [
      "/products/p440601843-0.png"
    ],
    "sizes": [
      "15 oz"
    ],
    "variants": [
      {
        "id": "evolve-borealis-black-mug-black-15-oz",
        "variantId": "5360367090",
        "sku": "6A34C10E6C765",
        "size": "15 oz",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      }
    ]
  },
  {
    "slug": "stealth-fit-evolve-full-zip-hoodie",
    "name": "Stealth Fit Evolve full zip hoodie",
    "subtitle": "Outerwear · made to order",
    "category": "outerwear",
    "collection": "prairies",
    "price": 5900,
    "externalId": "440600277",
    "tagline": "Where the signal dies, we come alive.",
    "description": "Stealth Fit Evolve full zip hoodie — Where the signal dies, we come alive. Printed and embroidered to order, then shipped across Canada and the continent.",
    "details": [
      "Made to order — printed/embroidered on demand",
      "Ships across Canada & North America",
      "1 colourway · sizes S, M, L, XL, 2XL, 3XL",
      "EVOLVE artwork — earned outside"
    ],
    "tone": [
      "#3a2f12",
      "#39ff14"
    ],
    "images": [
      "/products/p440600277-0.png"
    ],
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL",
      "3XL"
    ],
    "variants": [
      {
        "id": "stealth-fit-evolve-full-zip-hoodie-black-s",
        "variantId": "5360361034",
        "sku": "6A34BE729C6EC_S",
        "size": "S",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "stealth-fit-evolve-full-zip-hoodie-black-m",
        "variantId": "5360361035",
        "sku": "6A34BE729C6EC_M",
        "size": "M",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "stealth-fit-evolve-full-zip-hoodie-black-l",
        "variantId": "5360361036",
        "sku": "6A34BE729C6EC_L",
        "size": "L",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "stealth-fit-evolve-full-zip-hoodie-black-xl",
        "variantId": "5360361037",
        "sku": "6A34BE729C6EC_XL",
        "size": "XL",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "stealth-fit-evolve-full-zip-hoodie-black-2xl",
        "variantId": "5360361038",
        "sku": "6A34BE729C6EC_2XL",
        "size": "2XL",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      },
      {
        "id": "stealth-fit-evolve-full-zip-hoodie-black-3xl",
        "variantId": "5360361039",
        "sku": "6A34BE729C6EC_3XL",
        "size": "3XL",
        "color": "Black",
        "swatch": "#0a0a0a",
        "inStock": true
      }
    ]
  },
  {
    "slug": "evolve-fleece-zip-up-hoodie",
    "name": "Evolve fleece zip up hoodie",
    "subtitle": "Outerwear · made to order",
    "category": "outerwear",
    "collection": "coast",
    "price": 7550,
    "externalId": "440597762",
    "tagline": "Work hard. Play harder. Get outside.",
    "description": "Evolve fleece zip up hoodie — Work hard. Play harder. Get outside. Printed and embroidered to order, then shipped across Canada and the continent.",
    "details": [
      "Made to order — printed/embroidered on demand",
      "Ships across Canada & North America",
      "1 colourway · sizes S, M, L, XL, 2XL",
      "EVOLVE artwork — earned outside"
    ],
    "tone": [
      "#0c2c33",
      "#00ff41"
    ],
    "images": [
      "/products/p440597762-0.png"
    ],
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "2XL"
    ],
    "variants": [
      {
        "id": "evolve-fleece-zip-up-hoodie-charcoal-heather-s",
        "variantId": "5360349581",
        "sku": "6A34BA4671867_S",
        "size": "S",
        "color": "Charcoal Heather",
        "swatch": "#8a9099",
        "inStock": true
      },
      {
        "id": "evolve-fleece-zip-up-hoodie-charcoal-heather-m",
        "variantId": "5360349582",
        "sku": "6A34BA4671867_M",
        "size": "M",
        "color": "Charcoal Heather",
        "swatch": "#8a9099",
        "inStock": true
      },
      {
        "id": "evolve-fleece-zip-up-hoodie-charcoal-heather-l",
        "variantId": "5360349583",
        "sku": "6A34BA4671867_L",
        "size": "L",
        "color": "Charcoal Heather",
        "swatch": "#8a9099",
        "inStock": true
      },
      {
        "id": "evolve-fleece-zip-up-hoodie-charcoal-heather-xl",
        "variantId": "5360349584",
        "sku": "6A34BA4671867_XL",
        "size": "XL",
        "color": "Charcoal Heather",
        "swatch": "#8a9099",
        "inStock": true
      },
      {
        "id": "evolve-fleece-zip-up-hoodie-charcoal-heather-2xl",
        "variantId": "5360349585",
        "sku": "6A34BA4671867_2XL",
        "size": "2XL",
        "color": "Charcoal Heather",
        "swatch": "#8a9099",
        "inStock": true
      }
    ]
  }
];
